### ISSUE TITLE
Model repository unauthorised upon updating Archi and its plug-in

### ISSUE THREAD

**Issue by szuniga** [archimatetool/archi-modelrepository-plugin#101]
### Version of Archi, Operating System

Archi 4.4
Archi Model Repository 0.5.1.201904031126
Windows 10 Pro Version 1803
 
### Expected Behaviour

Remote Model Added

### Actual Behaviour

On updating Archi and the Model Repository to its latest version we are no longer able to access the remote repository due to not authorized messages, however we do have web access and on rolling back to earlier Archi and Model repository we do access the remote repository without a glitch.

We receive the messages: Fetching and then:

There was an error: http://<Microsoft TFS address>:8080/tfs/Collection/_git/Archi: not authorized.
There are no error log available to be seen.

### Steps to Reproduce the Behaviour
1. Configure a git Collection on Microsoft Teams Foundation.
2. Check that web access is authorized.
3. Upload an *.archimate model.
4. Try to access it via the Archi plug-in .

**Comment by szuniga** [comment]
Hi

0.3.6. However, the issues arises on Archi 4.4, because even with 0.3.6 the error shows up.

Best regards

**Comment by szuniga** [comment]
0.3.6 But the issue is with Archi 4.4, since even with the combination the problem shows up.

**Comment by Phillipus** [comment]
Somebody had a solution to a similar problem:

https://github.com/archimatetool/archi-modelrepository-plugin/issues/90#issuecomment-498232875

Did you try this?

**Comment by WayneCBarker** [comment]
Hi, 2 colleagues of mine are having the same issue. 

I can refresh and commit / publish to the repository with no issue but as soon as they try to import from remote model into workspace then it starts the process but during the fetch comes back with the following error.

![image](https://user-images.githubusercontent.com/3244770/60445141-e9625b80-9c1e-11e9-903e-c5713c790a63.png)

I have tried looking at the log but it does not seem like the plugin writes to the log file.

**Comment by WayneCBarker** [comment]
Ok, got it working by following this suggestion. https://github.com/archimatetool/archi-modelrepository-plugin/issues/90#issuecomment-499451085

**Comment by Phillipus** [comment]
Configuring TFS with the plug-in is probably a good candidate for a wiki entry here, should anyone wish to contribute.
