### ISSUE TITLE
Working with a public Git repository

### ISSUE THREAD

**Issue by stuartmaxwell** [archimatetool/archi-modelrepository-plugin#103]
I have a public git repository on a private Bitbucket server that is accessed over HTTPS but does not require credentials to read or write. If I try to access the repository without entering HTTP credentials, I get an error saying "Wrong Credentials".

**Comment by Phillipus** [comment]
If you use any user name and password does it work?

@jbsarrodie I'm not sure how this situation is handled normally? Perhaps credentials could be an option. I have no repo to test like this.

**Comment by Phillipus** [comment]
Actually I can see that this happens when Cloning a repo for the first time. An empty username or password will set this message. I can remove that check for the next version, but you could try putting any username and password in there for now.

**Comment by stuartmaxwell** [comment]
Thanks for the quick responses - I'll try that on Monday and will report back.
