### ISSUE TITLE
[BUG] Prolog error message when importing remote model to workspace

### ISSUE THREAD

**Issue by dagnils16** [archimatetool/archi-modelrepository-plugin#112]
Hi,

When trying to import a model to workspace choosing "Collaboration ->Import Remote Model to Workspace" and after the fetching progress is finished I get the following error: "There was an error: Content is not allowed in prolog"

Any idea why this error occur?

Thanks and regards,
Dag

![2019-11-15_151833](https://user-images.githubusercontent.com/46896699/68949916-600d8900-07bb-11ea-8f07-03280a32f4dc.png)

**Comment by Phillipus** [comment]
What is the model at the URL you are importing? Are you sure it's in the correct format for the collaboration plugin?

**Comment by dagnils16** [comment]
Thanks for feedback.

The model at the URL is an ArchiMate model which is based on a model exported from Sparx EA and imported to Archi using the Open Exchange import function. The next step I did was to choose the "Collaboration > Add local model to workspace and publish" which went well. The mentioned error occurs when another user is trying to import the model. 

- Dag

**Comment by dagnils16** [comment]
I found out the reason for my issue... I had entered the wrong URL.

/Dag
