### ISSUE TITLE
create new bransh when publishing

### ISSUE THREAD

**Issue by Ballzer0** [archimatetool/archi-modelrepository-plugin#116]
it would be nice if you could create a new branch instead of publishing directly to the master branch.

**Comment by Phillipus** [comment]
You can already create a new branch.

**Comment by Ballzer0** [comment]
sorry, worded that poorly. I would like a **Publish as a new branch** feature. It would mostly be an ease of life feature, allowing people to work of master and publish as a new branch.

**Comment by Ballzer0** [comment]
like, there could be a button under **publish changes** called **publish changes as a new branch**

**Comment by jbsarrodie** [comment]
> like, there could be a button under **publish changes** called **publish changes as a new branch**

That's not possible as your local copy of the model has to be an exact clone of the remote repository. Ie. commits have to be on the same branch on both side. So you have to first create the branch, then to commit, then to publish.

**Comment by Ballzer0** [comment]
Ouch, that's an anoying limitation. I just wanted to commit to a separate branch so that we could do pull requests instead of committing straight to master. Thanks for your time anyways, it's great insights to have 😁

**Comment by jbsarrodie** [comment]
> I just wanted to commit to a separate branch [...}

You can commit to a separate branch !
As Phil said, this is supported by the plugin: simply open the Branches view and create (and switch to) a new branch.

>[...] so that we could do pull requests instead of committing straight to master.

As said a lot of time here on GH and on the forum, you can't use pull requests with coArchi! There are a lot of additional things done when merging, including several anti corruption layers. Merging through another git tool or server will lead to a corrupted model.
