### ISSUE TITLE
[FeatureRequest] Compare 2 commits in branch. Compare 2 branches. 

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-modelrepository-plugin#122]
**User story 1**: User wants to get information about what is the difference between 2 branches. 

**Naive workflow**: 
- ctrl+Select 2 branches in "branches" view
-  right click on one of them, select "Compare branches using selected commits".
- Archi asks for commit to use for comparing for each branch;
- User selects a commit to compare for each branch
- Archi gives a view, where last commits from each branch are compared giving:
    - List of changed objects (objects added/deleted/changed, naming, doc, properties added/deleted/changed, etc.)
    - List of changed views (views added/deleted/changed, inside each view: object coordinates diff, object names diff, visual elements diff, etc.)
    - List of sketches changed (objects, naming, corrdinates, properties)
    - List of canvas changed (objects, naming, corrdinates, properties); 

User story 2: User wants to get information about what is the difference between commits in current branch. 

Workflow seems like same to be alsmost the same.

**Comment by WatchTh1** [comment]
Seems like my relative issue duplicates this one (in part of comparing commits). Maybe should be closed as Duplicate of #123 or split into two.

**Comment by Phillipus** [comment]
Something to look at for coArchi 2.
