### ISSUE TITLE
Hotkey for "Ok" button on "Commit" window

### ISSUE THREAD

**Issue by smirnoww** [archimatetool/archi-modelrepository-plugin#124]
Is there the ability to finish a commit without moving a hand from keyboard to mouse during commit message inputting?
I haven't found.
It would be convenient to done commit using a key combination (e.g. ctrl + Enter) while entering commit message. 
The keys "Tab" and "Enter" edit commit message. And there is no ability to switch focus to "Ok" button.

Thanks!

upd: and hotkey for "commit" button on the panel

**Comment by Phillipus** [comment]
On Windows, control traversal is with the Ctrl-Tab key combination.

**Comment by smirnoww** [comment]
> On Windows, control traversal is with the Ctrl-Tab key combination.
thanks!
what about hotkey for "commit changes" button on the panel?

**Comment by Phillipus** [comment]
Ctrl + Enter and Tab traversal will be in the next release.
