### ISSUE TITLE
Merge with conflict leads to "theirs" work to be lost (erased by "mine")

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-modelrepository-plugin#130]
_Logging this for my own investigation_

I very recently had two colleagues who faced a big issue with Archi 4.6 and coArchi 0.5.3.

In both cases, the publish their changes while their last publish had been done 1 or 2 months before. A one can imagine, they had some conflicts to solve. In both case they choose "theirs" to be sure to keep everything done by the rest of the team.

The result is a commit history not showing the usual merge commit labeled "Merge branch 'master' of ...", but instead it shows their lastest "real" commit (the one with a manually entered commit message) as a merge commit.

The impact is that in fact despite having chosen "theirs" in teh conflict solver, the model now contains their own (old) version and not a merge of their version and the current one on the git server.

I don't understand how this could happen, so I'm investigating....

**Comment by jbsarrodie** [comment]
I can now reproduce the bug:

_Hmmm, I did reproduce the bug but didn't take any screenshot. Now I'm trying to redo it I can't, so this is a work in progress_

Create a new model with only one view and publish it (using this one https://collaboration.archimatetool.com/jbsarrodie/Issue_130):
![image](https://user-images.githubusercontent.com/5757396/77679017-4878b500-6f92-11ea-9177-5007a66d0938.png)

From now on, we have two users (A and B) who work on this same version of the model)

User A updates the view a bit and publish it:
![image](https://user-images.githubusercontent.com/5757396/77679257-92fa3180-6f92-11ea-83e2-24f4565e7927.png)

User B creates a folder, move the view into it and do a lot of changes to the view:
![image](https://user-images.githubusercontent.com/5757396/77679472-deacdb00-6f92-11ea-9b50-435a93bc53f5.png)

A conflict is raised:
![image](https://user-images.githubusercontent.com/5757396/77679589-09972f00-6f93-11ea-9260-7909d0f31a2d.png)

This happens because there have been so many changes to the view that git is not able to see this has a a change on the same file (updated and moved), so git thinks it is a new view and thus thinks we've deleted the original one.

Let's continue (keep "Mine"):
_should have had an error message but no :-(
TO BE CONTINUED_

**Comment by jbsarrodie** [comment]
I can reproduce this bug also with coArchi 0.6.0. The only slight difference is that after the error message about `folder.xml`, the model is closed. But other than that, impact is the same at the end: User A loses all his/her work.

**Comment by jbsarrodie** [comment]
@Phillipus I've found the origin of this bug: RefreshModelAction was not reseting the repository to local state in this very specific case: we have had a conflict, conflict has been solved, merge is ok from a git point of view, but resulting model is corrupted and cannot be loaded by GraficoModelImporter.

I've commited a fix in branch `issue130`. Can you have a look and telle me if you think there is any side effect please?

**Comment by Phillipus** [comment]
Your change calls `loader.loadModel()` in both cases in the `if/else` clause. Would it make sense to only call it once (as in the existing code) but surround that with a `try/catch` block and throw the `ex` exception?

**Comment by jbsarrodie** [comment]
> Would it make sense to only call it once (as in the existing code) but surround that with a `try/catch` block and throw the `ex` exception?

The issue if that I can't call `resetToLocal()` outside the inner block

**Comment by Phillipus** [comment]
> The issue if that I can't call resetToLocal() outside the inner block

OK, I see that.

And should it re-throw the exception? Or quietly absorb it and return?

**Comment by jbsarrodie** [comment]
>And should it re-throw the exception? Or quietly absorb it and return?

We have to notify the user that something wrong happened, so forwarding the exception seems fine.
