### ISSUE TITLE
Collaboration Workspace no more shows model name in 0.6.0

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-modelrepository-plugin#135]
Collaboration Workspace should list models by their name, but in coArchi 0.6.0 I can only see the underlying folder name, not the model name:

My workspace in 0.5.3:
![image](https://user-images.githubusercontent.com/5757396/78252319-f2a48f80-74f2-11ea-9f04-97e3480a7e22.png)

My workspace in 0.6.0:
![image](https://user-images.githubusercontent.com/5757396/78252405-149e1200-74f3-11ea-9bc4-654daab71290.png)

This seems to be a regression.

**Comment by Phillipus** [comment]
I changed this in `ArchiRepository#getName()` in commit 3390836b in order to get the first instance of "name=" in folder.xml. Could you see what's happening there as all my repo names seem OK?

**Comment by Phillipus** [comment]
Hold on. I can reproduce this now...incoming fix...

**Comment by Phillipus** [comment]
Fixed. It seems an extra "!" made its way in there.

I'll release 0.6.2 also with you other fix in it.

**Comment by jbsarrodie** [comment]
>I'll release 0.6.2 also with your other fix in it.

Great, but if you want to wait some more days that's fine too (this might provide us some time to work on or fix other issues as well)

**Comment by Phillipus** [comment]
I prefer to do small incremental fixes especially for bugs. We got loads of numbers left...0.6.3, 0.6.4, 0.6.5... ;-)

**Comment by jbsarrodie** [comment]
As you want, and this makes sens especially for the really nasty bug fixed recently.

**Comment by Phillipus** [comment]
Did you further test your bug fix? I can't see that it would cause any issues other than fixing the bug.

**Comment by Phillipus** [comment]
Fixed in 0.6.2
