### ISSUE TITLE
allow branch names to include sub-folder structures

### ISSUE THREAD

**Issue by naebliss** [archimatetool/archi-modelrepository-plugin#141]
when creating a new branch the collaboration UI does not allow for creating branchnames like features/abc or bugfix/def to represent hierarchical directory grouping.
we follow the flow of branching from master and merging back using a pull-request similar to our code development.
it would be great if the same restrictions were present on branchnames as are in GIT

**Comment by Phillipus** [comment]
The "\" character is not allowed in git branch names.

**Comment by Phillipus** [comment]
> and merging back using a pull-request

Don't do that outside of Archi or you'll get problems.

**Comment by naebliss** [comment]
thanks for the clarification on usage on PR's.
i did a quick update of the original issue since GIT uses "/" to indicate hierarchical (directory) grouping.
i hope that clarifies the usage of this request somewhat

**Comment by Phillipus** [comment]
Unfortunately, we can't use the "\\" character either. This is a limitation of JGit, the git library that we use:

```
	/**
	 * Check validity of a ref name. It must not contain character that has
	 * a special meaning in a Git object reference expression. Some other
	 * dangerous characters are also excluded.
	 *
	 * For portability reasons '\' is excluded
	 *
	 * @param refName a {@link java.lang.String} object.
	 * @return true if refName is a valid ref name
	 */
	public static boolean isValidRefName(String refName) {
```

I know that it is possible to add the backslash in other git tools and the command line but JGit doesn't allow it.

**Comment by Phillipus** [comment]
(Previous comment edited - I meant "/" character not backslash)

**Comment by naebliss** [comment]
Thanks for clarifying, i think we can work with the limitation

**Comment by Phillipus** [comment]
Hold on - ignore what I said. You can use a "/" in the branch name, just not at the end of the branch. So, type in the name without the "/" character then move your cursor to where you want a "/" and type it.

I'll update the dialog box checking routine to allow you to type a "/" at the end of the branch name.

**Comment by Phillipus** [comment]
I've fixed the dialog box for entering a new branch name so that "." and "/" characters are allowed to be entered.

An error message is shown if these occur at the start or end of the branch name:

![1](https://user-images.githubusercontent.com/600504/87429757-2906a600-c5dc-11ea-862c-e3ed58b0707b.png)

 But you can still type in more characters to complete the name:

![2](https://user-images.githubusercontent.com/600504/87429815-3de33980-c5dc-11ea-83fd-3a2cc59ced42.png)

This will be in the next release.

**Comment by naebliss** [comment]
awesome! can't wait to use it

**Comment by Phillipus** [comment]
>  can't wait to use it

As mentioned above, you already can:

> Type in the name without the "/" character then move your cursor to where you want a "/" and type it.
