### ISSUE TITLE
Imported model isn't shown in model tree

### ISSUE THREAD

**Issue by kvaleev** [archimatetool/archi-modelrepository-plugin#142]
### Version of Archi, Operating System
Archi 4.7.1, MacOS 10.15.6

### Version of this plug-in
0.6.2.202004031233

### Any other plug-ins installed?
jArchi

### Expected Behaviour
After a new remote model imported, it's shown in the model tree.

### Actual Behaviour
The model is successfully fetched to a folder but isn't shown in a model tree, and there only way to add it – to manually edit `models.xml` file

### Steps to Reproduce the Behaviour
1. Create a new model
2. Upload the model to a remote server (Add Local Model to Workspace and Publish)
3. Close the initial model from Models tree
4. Import back the remote model (Import Remote Model to Workspace)

**Comment by Phillipus** [comment]
Don't do stage (4) if you already uploaded it.

If the Model is closed in the Models Tree, open itfrom the Collaboration Workspace window.
