### ISSUE TITLE
Unable to install, missing dependency ?

### ISSUE THREAD

**Issue by npigniergeodis** [archimatetool/archi-modelrepository-plugin#144]
### Version of Archi, Operating System
version 4.7.1, Windows 10

### Version of this plug-in
0.6.2

### Any other plug-ins installed?
none

### Expected Behaviour
It should install without error

### Actual Behaviour
Missing dependency plugin ?

### Steps to Reproduce the Behaviour
1. select org.archicontribs.modelrepository_0.6.2.202004031233.archiplugin in the "Install new"
![2020-08-10 11_53_36-Archi](https://user-images.githubusercontent.com/26485524/89771513-b7e5e000-db00-11ea-8424-3093f306d8b3.png)

2. after clicking "open"
![2020-08-10 11_54_35-Clipboard](https://user-images.githubusercontent.com/26485524/89771646-f4194080-db00-11ea-84fd-e4ad3bcbe23b.png)

Note that the "dropins" folder is empty

**Comment by Phillipus** [comment]
Please check access permission on the dropins folder and your temp folder. If the files cannot access these then there will be  a problem.

**Comment by npigniergeodis** [comment]
You're right, my "dropins" folder is not writeable, even as a local administrator... I'll check with my infrastructure team.
thanks.

**Comment by npigniergeodis** [comment]
not a archi problem

**Comment by Phillipus** [comment]
Just a note - the whole folder `.../Archi4` and its sub-folders should be writeable. If this is not possible you can set the data folders in the `Archi.ini` file:

```
-Dosgi.instance.area=@user.home/AppData/Roaming/Archi4
-Dosgi.configuration.area=@user.home/AppData/Roaming/Archi4/.config
-Dorg.eclipse.equinox.p2.reconciler.dropins.directory=%user.home%/AppData/Roaming/Archi4/dropins
```
