### ISSUE TITLE
Be able to easily distinguish models under repository source control and local models

### ISSUE THREAD

**Issue by kdrangej** [archimatetool/archi-modelrepository-plugin#146]
![image](https://user-images.githubusercontent.com/3890455/92372857-d2aa7500-f0fd-11ea-8007-910c9abb12e4.png)

I believe it would be useful if a model under repository source control had a different icon in the model tree view. As pr. today it is not possible to distinguish between the different tree node elements. 

This is an issue because I need to apply a different process to the models that are not under source control when doing changes to the model.

**Comment by Phillipus** [comment]
In fact, because the model repository is a separate plug-in the models tree is not aware of it (same for any down-steam plug-in). Really, models under source control should be managed in the "Collaboration Workspace" tab.
