### ISSUE TITLE
Unable to add model to workspace

### ISSUE THREAD

**Issue by WayneCBarker** [archimatetool/archi-modelrepository-plugin#149]
Unable to add model to workspace (Bitbucket)

I get the following error :There was an error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target."

![image](https://user-images.githubusercontent.com/3244770/93771639-1339e080-fc1e-11ea-8cf0-bbece9151f2a.png)

Windows Ver 10.0.16299.1625
Arch 4.7.1
Build 202007151058

### Version of this plug-in
org.archicontribs.modelrepository_0.6.2.202004031233.archiplugin

### Any other plug-ins installed?
No.

### Expected Behaviour
Model should be added to workspace.

### Actual Behaviour
Error as described above is given.

### Steps to Reproduce the Behaviour
1. Collaboration -> Add local model to workspace and publsih
2. Fill in URL and username and password.
3. Keep Store user name and password box selected
4. Click Ok.
5. Boom - Error.

**Comment by jbsarrodie** [comment]
Do you use an enterprise setup of bitbuckep which uses a  certificate comming from a local PKI?

If yes you most certainly have to add those root certificates to Archi's JRE or try to edit Archi.ini to use Windows-root. Try looking it up on previous issues. If you don't find needed information then tell me and I'll get you the links (don't have them at hand).

**Comment by Phillipus** [comment]
Is this relevant?

https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Use-SSL-TLS-with-local-or-private-PKI

**Comment by WayneCBarker** [comment]
OK cool, added the PKI entries as per the link above.

Now I get this. Is there not a error log with more detailed errors somewhere?

![image](https://user-images.githubusercontent.com/3244770/93849404-5c387600-fcac-11ea-9037-71cf69ae28c9.png)

**Comment by Phillipus** [comment]
> Is there not a error log with more detailed errors somewhere?

Unfortunately, JGit, the Java Git library, does not do logging. All we get is an exception for a git action which is shown in the error dialog.

**Comment by WatchTh1** [comment]
Has the same error as topicstarter on bitbucket server deployed in public internet with let's encrypt certificate.
git clone works as expected.
root certificate exists both in system keystore, and Archi keystore. (keytool throws : already exists error ).

Is this possible to configure git binary should be used to archi ? 
I mean tell it to use system one.
