### ISSUE TITLE
Mac Archi 4.7.1 plugin 0.6.2. git push says not unauthorized user 

### ISSUE THREAD

**Issue by alberttwong** [archimatetool/archi-modelrepository-plugin#150]
I have GPG and SSH keys uploaded to github.   No branch protection for the project.   Can't find the logs on my mac.  Where are they?

**Comment by Phillipus** [comment]
Please provide more info about your type of connection, authentication, etc.

> Can't find the logs on my mac. Where are they?

The Configuration and Error Log can be accessed in Archi by selecting the “About Archi” menu item. In the dialog box press the “Installation Details” button, then select the “Configuration” tab and press the “View Error Log” button.

**Comment by alberttwong** [comment]
"View Error Log" button is greyed out.   I cannot press it.

**Comment by Phillipus** [comment]
> "View Error Log" button is greyed out. I cannot press it.

That will mean there is no error log. On a Mac the path to the log is: 

`/Users/username/Library/Application Support/Archi4/.metadata/.log`

Please provide more info about your type of connection, authentication details, steps taken (what were you doing) etc, etc.

**Comment by alberttwong** [comment]
no logs in `/Users/alberttwong/Library/Application Support/Archi4/.metadata/.log`.   There is only a `.plugins'  folder in '.metadata'.

>> type of connection, authentication details, 

For the pull, I put in my username and password and downloaded my github project.  There was no problem there.   As far as the push, it prompted me again and I put in my name, username and password.    In the settings, I did see that it found my ~home/.ssh/id_rsa key.   Which is the same key I have uploaded to github.     I can't think that I did anything unique.   If I was just using git on the CLI, I do use my GPG key to sign my commits while also using my username and password.     Typically I have branch security (all commits should be signed) but I deleted it when I ran into auth problems with archi.

**Comment by Phillipus** [comment]
GPG is not supported in coArchi if that's any help. See https://github.com/archimatetool/archi-modelrepository-plugin/issues/114

**Comment by Phillipus** [comment]
And check this https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

**Comment by alberttwong** [comment]
So i also hit https://github.com/archimatetool/archi-modelrepository-plugin/issues/88

I then regen my ssh to PEM and used `git@github.com:alberttwong/archi_cloudnative.git` and it's now working.  Thanks!
