### ISSUE TITLE
Using a Proxy server cannot authenticate - "java.net.ProtocolException: Server redirected too many times (20)"

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-modelrepository-plugin#153]
I'm trying to test coArchi using a local proxy server that is set to use authentication. I've tested with CCProxy and a proxy server on my NAS. Same problem. So I don't think it's a problem to do with the proxy server.

The error is:

```
org.eclipse.jgit.api.errors.TransportException: https://github.com/Phillipus/poo.git: cannot open git-upload-pack
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:255)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:290)

Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/Phillipus/poo.git: cannot open git-upload-pack
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:600)

Caused by: java.net.ProtocolException: Server redirected too many times (20)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:115)
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:207)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:514)
```

Here's the part of  `ProxyAuthenticator` that returns the user name and password when connecting:

```java
Authenticator.setDefault(new Authenticator() {
    @Override
    public PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(username, password.toCharArray());
    }
});

```

`getPasswordAuthentication()` is being called many times (20) leading to the error.

The Proxy servers are working for general browser and Smartgit access.

I've tried all the usual things suggested when you Google "java.net.ProtocolException: Server redirected too many times (20)"

This used to work for me but no longer. I don't know what's changed.

Is anyone using coArchi successfully with a proxy server?

**Comment by Phillipus** [comment]
Found something.

The first time the `Authenticator` is called it wants the username/password for the proxy. The second time it is called it wants the username/password for the repository URL. As we are using the same `Authenticator` instance we are returning the username/password for the proxy in both cases.

It didn't use to work like this. Perhaps a change in jGit?

Has anyone got the proxy working?

**Comment by Phillipus** [comment]
> It didn't use to work like this. Perhaps a change in jGit?

I tested against older versions of coArchi - same problem.

Perhaps it never worked? Or a change in Java?

**Comment by Phillipus** [comment]
I've figured out a fix for this. But I have questions:

- Did the proxy in coArchi ever work?
- If it did work, why does it not work now?
- If it didn't work, why did I think it did work?

**Comment by jbsarrodie** [comment]
It did work (and still works in 0.6.2): me and several people in my team use it.

**Comment by Phillipus** [comment]
That is very strange. I've traced the code and here is what is happening:

If a proxy is being used, this code is used to return the credentials for the proxy host:

```
Authenticator.setDefault(new Authenticator() {
    @Override
    public PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(username, password.toCharArray());
    }
});
```

But from this point on, _all_ authentication requests divert to this method. The proxy credentials and the git repo credentials. So if this is returning the credentials for the proxy access, it succeeds but fails for the repo credentials and keeps trying until it fails 20 times. It will only work if the credentials for the proxy and the git repo are the same.

**Comment by Phillipus** [comment]
It should be like this:

```java
Authenticator.setDefault(new Authenticator() {
        @Override
        public PasswordAuthentication getPasswordAuthentication() {
            // This is the proxy so return those credentials
            if (super.getRequestingHost().equals(proxyHost)) {
                return new PasswordAuthentication(proxyUsername, proxyPassword.toCharArray());
            }
            // This is not the proxy so return null so that the jGit's credentials authenticator is called instead
            return null;
        }
});
```

**Comment by jbsarrodie** [comment]
> It will only work if the credentials for the proxy and the git repo are the same.

They are in our context as we use a Single Sign-On platform under the hood.

**Comment by Phillipus** [comment]
OK, but this needs fixing for cases where the credentials are different, The current implementation is wrong which will explain why some users get the `cannot open git-upload-pack` error when using a proxy.

The proper implementation is:

```java
Authenticator.setDefault(new Authenticator() {
    @Override
    public PasswordAuthentication getPasswordAuthentication() {
        // If proxy, return its credentials
        // Otherwise the requested URL is the endpoint (and not the proxy host)
        // In this case the authentication should not be proxy so return null (and JGit CredentialsProvider will be used)
        if(getRequestorType() == RequestorType.PROXY) {
            return new PasswordAuthentication(npw.getUsername(), npw.getPassword().toCharArray());
        }
        return null;
    }
});
```

This will return the correct credentials for the proxy. If it is not the proxy requesting the details it will use JGit's authentication handler (our `CredentialsAuthenticator` class) which returns the credentials stored for the repo.

I think it used to work for me in the early days because I had a local GitBlit test server that used the same credentials as CCProxy.

@jbsarrodie Are you storing the username/password for each repository? With this fix it will need to get those.

**Comment by Phillipus** [comment]
> @jbsarrodie Are you storing the username/password for each repository? With this fix it will need to get those.

Or at least asking for these credentials in the dialog?

**Comment by Phillipus** [comment]
Some more information for reference:

- A `java.net.Authenticator` has to be used for the proxy credentials but it must not be used for the end-point (repo) credentials. In that case, null must be returned so JGit can use a `UsernamePasswordCredentialsProvider` as returned in our `CredentialsAuthenticator`

- Once a successful proxy authentication is done, Java caches these credentials and does not call `getPasswordAuthentication()` for the proxy credentials again. This means that if the user changes their proxy credentials in Preferences they will not be used until Archi is re-started. This has always been the case and is a known issue with Java for some years.

**Comment by Phillipus** [comment]
This is fixed now in branch `encryption` as part of the changes there. Our `ProxyAuthenticator` is set up once at the beginning of the session and only re-established if the preferences change.
