### ISSUE TITLE
Incorrect display of object ids in the name and in the "id" property

### ISSUE THREAD

**Issue by rdm1234** [archimatetool/archi-modelrepository-plugin#154]
### Version of Archi, Operating System
Archi version: 4.7.1.
OS: Windows 10.

### Version of this plug-in
0.6.2.

### Any other plug-ins installed?
No other plug-ins.

### Expected Behaviour
For objects, the id property has a value in the guid format (example: `id="0a2084f0-9ee8-42ba-bb4a-b909c27bf943"`).
The git object name has the format `{ObjectTypeName}_{Guid}.xml` (example: `BusinessRole_0a2084f0-9ee8-42ba-bb4a-b909c27bf943.xml`).

![image](https://user-images.githubusercontent.com/20128252/95662100-2c5af080-0b3d-11eb-8c37-fc9fd18a98bc.png)

### Actual Behaviour
The id property has a value in the format `id_{shortGuid}` (example: `id="id-55b13613d71b41048339c0d339f37af8"`).
The object name has the format `{ObjectTypeName}_id-{shortGuid}.xml` (example: `BusinessRole_id-55b13613d71b41048339c0d339f37af8.xml`).

![image](https://user-images.githubusercontent.com/20128252/95662103-3a107600-0b3d-11eb-9d8d-d36aca290499.png)

### Steps to Reproduce the Behaviour
1. Create new object
2. Push commit

**Comment by jbsarrodie** [comment]
Ids have been changed in Archi 4.7  to be always prefixed by 'id-'. This makes sure that generated ids are always valid in an XML context and thus enable round-trip when using exchange file format.

See https://github.com/archimatetool/archi/issues/625 for more information

**Comment by Phillipus** [comment]
In fact, you shouldn't care what the format is. Don't look into the internals, this stuff is not API.
