### ISSUE TITLE
Trying to publish result in a message "There was an error" with no more information

### ISSUE THREAD

**Issue by JHU2034** [archimatetool/archi-modelrepository-plugin#157]
The contexte:

Archi in version 	4.7.1.202007151058
OS Windows Version	10.0.17763 Numéro 17763
Archi-model repository in version 0.6.2.202004031233
No other plugin

Trying to publish changes from synchronize model in Github produces the following sequence:

1 - "Refreshing from remote"
2 - "Publising to remote"
3 - "There was an error" with no more information

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by jbsarrodie** [comment]
Hi,

I'm sorry, but there's nothing more we can do to help. Did you tried to look at the Archi error log (Help > About Archi > Installation Details > Configuration Tab > View Error Log button) ?

**Comment by Phillipus** [comment]
In addition to what @jbsarrodie said, you should have a look through the wiki and issues here to determine if the problem could arise from:

- proxy settings
- certificates
- access privileges
- connection settings

In fact there are several things that should be checked.

**Comment by Phillipus** [comment]
No more info from OP = closed.
