### ISSUE TITLE
Add model to existing repository SSH, not possible 

### ISSUE THREAD

**Issue by szaluzhskiy** [archimatetool/archi-modelrepository-plugin#158]
### Version of Archi, Operating System
Version 4.7.1
Build 202007151058
Windows 10

### Version of this plug-in
0.6.2.202004031233

### Any other plug-ins installed?
no

### Expected Behaviour
Create model locally.
Call Add local model to Workspace and publish 
Then publish model

### Actual Behaviour
Error invalid privatekey

### Steps to Reproduce the Behaviour
1. Create model, add some elements and views
2. Create new GIT repository on external resource (Bitbicket, gitlab, any)
3. Go to Archi select Add Local Model to Workspace and Publish
4. Press button publish
5. Error invalid privatekey 

I was trying to change key via configuration... but this does not help

**Comment by szaluzhskiy** [comment]
I foolowed [doc](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Manage-Workspace) chapter _Add local model to Workspace_

**Comment by waacot** [comment]
Hello @szaluzhskiy,

I use to work with HTTPS, but after a short try on my github repository, it  seems to work fine.
I previously add my generate private key on Github to authorize SSH handshake between Archi(c) and github.
From a terminal console, have you tried a simple "git clone git@github.com:waacot/archi-test1.git" on a temporary directory.
Of course replace : git@github.com:waacot/archi-test1.git by your own git repo ;-) 
Regards,
Laurent

**Comment by szaluzhskiy** [comment]
@waacot 
  Yes, I try to check out git repo to local folder and then "Add Local model to workspace and Publish". 
![image](https://user-images.githubusercontent.com/3520290/101897473-a77f6800-3bbb-11eb-9c97-5c72f3e229a2.png)

**Comment by szaluzhskiy** [comment]
Btw I did a check with GitHub repository and result is the same, I mean same error in Archi.

**Comment by Phillipus** [comment]
Make sure you follow the instructions here when setting up SSH:

https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

**Comment by szaluzhskiy** [comment]
Looks like my GIT repository (corporative one), does not support PEM keys. Is it possible to use RSA key pair like this?

_ssh-keygen -t rsa -b 2048_

**Comment by Phillipus** [comment]
> Is it possible to use RSA key pair like this?

I don't know, did you try? coArchi uses the JSch SSH library which is quite old:

http://www.jcraft.com/jsch/

For coArchi 2 we might consider using the Apache Mina SSHD library which I think supports more SSH key types. Needs more investigation.

**Comment by Phillipus** [comment]
Might be some useful info here - https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

**Comment by szaluzhskiy** [comment]
If configure key with instruction - https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication then it's working. You can close the issue. Thanks for support!

**Comment by Phillipus** [comment]
> You can close the issue.
