### ISSUE TITLE
Password-only repository access to GitHub is depreciating

### ISSUE THREAD

**Issue by weleoka** [archimatetool/archi-modelrepository-plugin#159]
When working with github we now get the following notice after pushing with Archi Modelrepository Plugin:

> Hi @myusername
> 
> You recently used a password to access the repository at myusername/my-archirepo with git using JGit/5.3.0.201903130848-r.
> 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

### Version of this plug-in
v0.6.2.202004031233
with dependency on: JGit/5.3.0.201903130848-r.

**Comment by Phillipus** [comment]
You can generate a token and use that instead of a password. Just put it in the password field.

**Comment by Phillipus** [comment]
I'll close this as there's nothing to fix on Archi's side.

**Comment by Phillipus** [comment]
BTW coArchi 0.7.0 is available and all passwords are stored in encrypted files now. See https://forum.archimatetool.com/index.php?topic=955.msg5210#msg5210
