### ISSUE TITLE
Using a Github PAT, application constantly asks for password

### ISSUE THREAD

**Issue by scottwalkerwmda** [archimatetool/archi-modelrepository-plugin#167]
Authenticated using a GitHub PAT. able to push and pull  model but every time it re asks for the information on the remote repository including the password.

The box for storing the password is ticked.

Any ideas?

**Comment by jbsarrodie** [comment]
That's a strange behavior that I never experienced. Can you provide more information (version of Archi and coArchi, exact steps to reproduce the issue, screenshots of dialogs...).

**Comment by scottwalkerwmda** [comment]
I think the problem could be to do with my other ticket. 
https://github.com/archimatetool/archi-modelrepository-plugin/issues/168 

I expected that multiple models could be in a repository, so when I want to add a local model and push it, it asks for the connection information again. If I'm not allowed multiple models in a repo, then Archi is saying "ok, for this new model, I need a new repo"
Would that make sense?

**Comment by jbsarrodie** [comment]
> Would that make sense?

Not sure. Could you please describe the list of steps you followed and add some screenshots. I'm afraid we won't be able to help without more information.
