### ISSUE TITLE
Unable to have multiple models in a repository?

### ISSUE THREAD

**Issue by scottwalkerwmda** [archimatetool/archi-modelrepository-plugin#168]
Every time I try to add a new model to a repo, it is always trying overwriting the previous model. Meaning that I can only ever have one model in a repo.

Am I making a mistake or is this the intention?

**Comment by jbsarrodie** [comment]
Hi, in coArchi, each model is stored into its own repository.

**Comment by Phillipus** [comment]
I'll close this as this is intended behaviour.
