### ISSUE TITLE
 Allow multiple models in the same repository,

### ISSUE THREAD

**Issue by scottwalkerwmda** [archimatetool/archi-modelrepository-plugin#169]
As a Software developer, I want to use Archi for my diagrams.
I'd like to incorporate all of these diagrams in the same repository as my code base. For example, We have functional flow diagrams, database diagrams, communication diagrams that are all apart of the same project and it would make sense for us to have them all in the same repository

**Comment by jbsarrodie** [comment]
Hi,

There seems to be some misunderstanding here.

In ArchiMate (and thus in Archi), a model contains multiple elements, relationships and diagrams (called views). coArchi (aka model repository plugin) allows you to collaborate on models by storing models in their own git repository.

So at the end, you have only one model per repository, but you can have any number of diagram is such model.
