### ISSUE TITLE
Authentication Requirements for Git have changed and coArchi can't refresh/publish Models

### ISSUE THREAD

**Issue by andrejs86** [archimatetool/archi-modelrepository-plugin#172]
### Version of Archi, Operating System
Archi 4.8.1, Windows 10 Enterprise 20H2

### Version of this plug-in
Archi Collaboration (coArchi) 0.7.1.202102021056

### Any other plug-ins installed?
No other plugin installed

### Expected Behaviour
Commit and Push Archi Model to Github repo successfully.

### Actual Behaviour
Error when trying to access Github repo.
Github is changing its authentication requirements as per: [https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)

### Steps to Reproduce the Behaviour
1. Try to refresh Model
or
1. Make any change
2. Try to Publish Model

![image](https://user-images.githubusercontent.com/35151217/124009893-842fd500-d9b4-11eb-86fb-acb89b63149d.png)

Is there a way to use SSH or any method other than "username and password"?

**Comment by Phillipus** [comment]
See https://github.com/archimatetool/archi-modelrepository-plugin/issues/159

**Comment by andrejs86** [comment]
Thank you!
