### ISSUE TITLE
Invalid private key when connecting Github with ssh-Authentication

### ISSUE THREAD

**Issue by Chazaam** [archimatetool/archi-modelrepository-plugin#174]
Hello

I follow these instructions to work with Archimate Collaboration tools :
https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

Mac OS Big Sur version 11.2.3
Archimate Version : 4.8.1 found here https://www.archimatetool.com/download/
coArchi Version 0.7.1 found here https://www.archimatetool.com/plugins/

I get this error when i try to import a remote model to my workspace : 
"There was an error: git@[mypath.git]... invalid privatekey : [B@1d6590b4"

Theses issues mentionned that problem but i'm not sure that the solution is clearly identify ?
https://github.com/archimatetool/archi-modelrepository-plugin/issues/81
https://github.com/archimatetool/archi-modelrepository-plugin/issues/42

Is anyone else concern by this problem ?

**Comment by Phillipus** [comment]
Did you follow these instructions?

https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

**Comment by jbsarrodie** [comment]
@Phillipus unless he edited his message, he did:

>I follow these instructions to work with Archimate Collaboration tools :
https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

**Comment by Phillipus** [comment]
> @Phillipus unless he edited his message, he did:
> 
> > I follow these instructions to work with Archimate Collaboration tools :
> > https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication

I never read the first few lines of a message. ;-)

@Chazaam Sorry, I can't help more with this.

**Comment by Phillipus** [comment]
> Mac OS Big Sur version 11.2.3

It might be a Mac thing. I found this: 

https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

**Comment by Chazaam** [comment]
> > Mac OS Big Sur version 11.2.3
> 
> It might be a Mac thing. I found this:
> 
> https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

Yes I found it too. But nothing change on my side. So strange...

**Comment by sebastienbrunkyndryl** [comment]
Hello, 

I have the same issue on my Mac OS big Sur version 11.5.2, Archimate tool 4.8.1 and collaboration plugin 0.7.1

It exist a precedence between Archimate configuration and the .ssh/config file. If the configuration is not aligned it doesn't work. 

Do you think that you can solve this issue. outside Archimate I work with edc25519 encryption and archimate tool required rsa4096.

**Comment by Phillipus** [comment]
> Do you think that you can solve this issue. outside Archimate I work with edc25519 encryption and archimate tool required rsa4096.

It requires further research into the SSH requirements of JGit and the JSch libraries.

As this is open source, we are open to contributions and advice on the issue.

Unless there is an easy fix, we won't be looking at this until coArchi 2 next year. Or you could use https.

**Comment by sebastienbrunkyndryl** [comment]
thank's for your reply @Phillipus , I'll modify my git wrapper by using a custom .ssh/config file as an alternative.

**Comment by codeadmin-peritiae** [comment]
I solved creating a Personal Access Token:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
and using the PAT instead of the password for HTTPS connections in Archi.
