### ISSUE TITLE
Feature request: Do not require primary password

### ISSUE THREAD

**Issue by decentropy** [archimatetool/archi-modelrepository-plugin#176]
I cannot clear or turn off the "Primary Password" for publishing.

The use case is:
- I have a remote environment with Archi, which is shared by multiple users.
- Their Archi is connected to git as a 'guest' user, with access to a 'Dev' branch... which I review & merge into master as needed.
- I would like these users to refresh and publish (without being prompted for password).

**Comment by Phillipus** [comment]
The primary password is baked into coArchi for storing repo passwords. We won't be changing this.

**Comment by adgerrits** [comment]
I struggled with the 'primary password' feature as well. It suddenly started asking for the password without any context information. The CoArchi documentation doesn't document the feature (yet). In the end via the Preferences/Collaboration menu I the 'change primary password' option. Don't know if it is a bit buggy or I forgot a previous entered password but anyway the information/documentation can be improved.

**Comment by Phillipus** [comment]
Hi Ad,

we did add some documentation here - https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Setup-and-Configuration#authentication - the idea is to secure all repo passwords with one main password. We'll certainly try to improve the experience in coArchi 2.

Phil

**Comment by adgerrits** [comment]
Hi Phil, thanks. 

As I said: maybe it was my fault and I entered a password earlier but I’m quit sure  I didn’t But now it works like a charm like as I am used to from Archi!

Gr Ad

**Comment by lcrowleyEPRI** [comment]
Hi,

I read the documentation that Phillipus mentioned but it does not tell you how to open the Configuration window from Archi directly. Does anyone know how to open that menu? I'm looking to access the primary password settings.

Laura

**Comment by Phillipus** [comment]
@lcrowleyEPRI That is in Archi's Preferences.

**Comment by ciklysta** [comment]
We use solely ssh keys to access git repos (the key stored on an encrypted disk, hence no need for encryption of the key itself), I still have to to set up the _primary password_. However an empty one is not accepted, therefore I use single space char. It prompts to enter it on fetch or push. It would be really nice if - for this use case - I was not bothered with the _primary password_ at all.

**Comment by Phillipus** [comment]
I've been experimenting with different encryption methods a lot lately. Not requiring a primary password is one option. It's under investigation for a future version.

**Comment by ciklysta** [comment]
Thank you much for all your efforts.
