### ISSUE TITLE
Secure connection to [URL] could not be established because of SSL problems

### ISSUE THREAD

**Issue by carld** [archimatetool/archi-modelrepository-plugin#180]
### Version of Archi, Operating System

Windows 10, Archi 4.9.0 Build 202110121300

### Version of this plug-in

coArchi 0.8.0.202110121448

### Expected Behaviour

Git client fetches from remote repository (via https url to git repository hosted on Azure DevOps) to clone a local copy.

### Actual Behaviour

Dialog box indicates SSL problems: "There was an error: [URL] Secure connection to [URL] could not be established because of SSL problems.

On a laptop that already had fetched the remote repository and had a local git repository I was able to move past the error by adding `sslVerify = false` to the git config file, .git/config

On a laptop that is pristine and no repository exists and there's no config file to amend with the above, I could not find a workaround.

### Steps to Reproduce the Behaviour
1. In Archi, Collaboration, "Import Remote Model to Workspace"
2. In dialog box, enter a Primary password
3. In dialog box, enter URL, username (domain email address), and in password enter the Personal Access Token, generated in Azure DevOps, check "store user name and password".
.

**Comment by carld** [comment]
I have updated the wiki pages and will close this issue.

**Comment by Phillipus** [comment]
> I have updated the wiki pages and will close this issue.

Thanks!

**Comment by shubham11kale** [comment]
Select your application from upper ribbon click on "Edit Configurations" from there. And then click on "Add VM Options". Add below lines in that field:
-Djavax.net.ssl.trustStore=NUL
-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT

This helped me
