### ISSUE TITLE
GitHub Action for deploy Archi (coArchi) reporsts

### ISSUE THREAD

**Issue by WoozyMasta** [archimatetool/archi-modelrepository-plugin#184]
Greetings

I made a [project][] with [container][] and a [GitHub Action][] here to automatically publish Archi reports to GitHub and GitLab pages.

[View GitHub Pages demo][demo-gh-pages] | [Example GitHub repository][example-gh]
[View GitLab Pages demo][demo-gl-pages] | [Example GitLab repository][example-gl]

Maybe you can add a link to this in the wiki of the project?

I tried updating the wiki a few months ago, but my edit was removed, the project is now more mature and stable. Can I or someone add this information to help people who need this kind of automation easier to find a ready-made solution? 

[project]: https://github.com/WoozyMasta/archimate-ci-image
[container]: https://github.com/WoozyMasta/archimate-ci-image/pkgs/container/archimate-ci-image
[GitHub Action]: https://github.com/marketplace/actions/deploy-archi-report
[example-gh]: https://github.com/WoozyMasta/archimate-ci-image-example.git
[demo-gh-pages]: https://woozymasta.github.io/archimate-ci-image-example/?view=6213
[example-gl]: https://gitlab.com/WoozyMasta/archimate-ci-image-example
[demo-gl-pages]: https://woozymasta.gitlab.io/archimate-ci-image-example/?view=6213

**Comment by Phillipus** [comment]
I removed your edit because it was at the top-level (https://github.com/archimatetool/archi-modelrepository-plugin/wiki/_Sidebar/f32c9b99d46ee0a526842563c21faa56d6020fe9)

I guess we could have some overall wiki page like "Other Resources" or a similar title so we can add links to this type of thing.

@jbsarrodie What do you think?

**Comment by jbsarrodie** [comment]
> I guess we could have some overall wiki page like "Other Resources" or a similar title so we can add links to this type of thing.

Yes, and also a "Security" or "Authentication" section for SSH, SSL/TLS...

I'm working on it

**Comment by jbsarrodie** [comment]
> I'm working on it

Done

**Comment by Phillipus** [comment]
Ta!
