### ISSUE TITLE
Need command line option to export Grafico folder and files with and without git option

### ISSUE THREAD

**Issue by faiyazshk** [archimatetool/archi-modelrepository-plugin#186]
Enhancement

### Version of Archi, Operating System

4.9.2

### Version of this plug-in

0.8.1
### Any other plug-ins installed?

No
### Expected Behaviour

There should be a command line option to export archimate file to grafico folder and file format with and without git option

**Comment by Phillipus** [comment]
What's the use case?

Exporting an Archi model to the disaggregated "Grafico" format is an internal process that is part of coArchi, and is not a suitable candidate for a command line option.

**Comment by faiyazshk** [comment]
We have a process which generate base archimate models in a single files from system of records and this is used by architects to generate views and work on it. If architects need to collaborate coarchi is good for it but it works on grafico format and hence we want to save the file to start with grafico format and later on also it would be easy to compare between generated file and coarchi.

**Comment by Phillipus** [comment]
Sorry, but this won't be implemented (at least not by me). In fact, for coArchi 2 we won't use this format at all.

So. I'll close this issue.
