### ISSUE TITLE
Collaboration/Add local model to workspace and publish

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi-modelrepository-plugin#187]
### Version of Archi
 4.9.2

### Archi Plug-ins
Collaboration

### Operating System
Win10 pro

### Expected Behaviour

We have created a local model and we would like to push it into the collaboration workspace.

### Actual Behaviour

We do have some difficulties:
- We have created a project in GIT.
- We have a local model with some viewes, building block...
- Whe would like to create the model in the workspace: Collaboration/Add local model to workspace and publish
-  We get an error with some relationships and the file temp.archimate is not created in the directory: C:\Users\chdes\AppData\Roaming\Archi4\model-repository\cartographie-si\.git\temp.archimate

### Steps to Reproduce the Behaviour
1.Collaboration/Add local model to workspace
2.Publish
3.
![Image2](https://user-images.githubusercontent.com/47627451/153459053-d9538737-e7e8-4f8d-bf74-7cd4b8d269aa.jpg)

**Comment by Phillipus** [comment]
[Moved this to the coArchi issue tracker]

Hi,

is the original local model (before you tried to import to workspace) OK?

**Comment by chdessus** [comment]
Yes, I ask my client if I can send it to you. 
I did a "Validate model" and I get no errors, only some advices. here are the results I get.
![Image3 jpeg](https://user-images.githubusercontent.com/47627451/153466992-49b74fff-2747-4c4b-9a57-0a148cf0c939.JPG)


Thank you.

**Comment by chdessus** [comment]
Hello again,
I now have an account and a laptop at my client premices. It took time but I have it now. I redo the tests and I get a SSL error.
I used a HTTPS URL copied from the clone button in GITLAB.
Here is the attached image. 
Thank you again for your support. 
ChristineD


![erreur ENX SSL archi collaboration 2022 02 23](https://user-images.githubusercontent.com/47627451/155367286-125786c4-628e-4d15-91b2-9ebd0a14d5a5.jpg)

**Comment by DanApostol** [comment]
Hello,

it might be a ssl handshake problem, since you're on client infrastructure, getting to that url it probably uses getting the route through the intranet proxy which can maybe change the ssl certificate with company's IT own certificate, in order to observe the outbound traffic. Try access directly the IP of git server or put the url into exceptions list....

Regards,
Dan.

**Comment by chdessus** [comment]
Thank you. We did solve the SSL pb. Now we are using SSH connection. Another error appears related to "Profile reference is orphaned. I rise a new issue. You can close this one.

**Comment by chdessus** [comment]
Thank you. We did solve the SSL pb. Now we are using SSH connection. Another error appears related to "Profile reference is orphaned. I rise a new issue. You can close this one.
