### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by vovy** [archimatetool/archi-modelrepository-plugin#188]
The error log does not contain any record of the behavior.

### Version of Archi, Operating System

Archi 4.9.2, Windows 10

### Version of this plug-in

0.8.1

### Any other plug-ins installed?

no

### Expected Behaviour

The collaboration worked as documented until the computer went to sleep over the weeken.

### Actual Behaviour

Seemingly any operation on the branches causes java.lang.reflect.InvoctionTargetException
![image](https://user-images.githubusercontent.com/17003810/153884862-18a8ec64-272b-46e1-8053-7e76ebe3b634.png)

### Steps to Reproduce the Behaviour
1. open Archi
2. open a model from local workspace
3. try to do any online sync (e.g. switch, refresh, merge)

**Comment by Phillipus** [comment]
Unless there are exact steps to reproduce this will be hard to pinpoint.

Try closing and re-opening Archi. And make sure "Refresh remote model status in the background" is off in Preferences.

You could also delete this folder and re-start Archi:

`<user>/AppData/Roaming/Archi4/.config`

**Comment by vovy** [comment]
thank you for the fast response.

i can only add, that i pushed any of the icons to switch branch, refresh, merge, and got the errors in screenshots. it worked on Friday, now it does not. nothing changed inbetween really.

i had version 4.9.0 and replaced it with 4.9.2 before submitting the issue, but it did not help. i tried to reinstall the plugin, too. did not help.

Refresh remote model status in the background was already off.

i tried to clean .config the folder as per your suggestion. no luck. maybe another cache somewhere?

**Comment by vovy** [comment]
a completely new install elsewhere after deleting the whole <user>/AppData/Roaming/Archi4 folder works now.

let's see, if i manage to break it again, when the PC goes to sleep next time.
