### ISSUE TITLE
Cannot Publish to GitHub website when model is set to private

### ISSUE THREAD

**Issue by MvanRooijen** [archimatetool/archi-modelrepository-plugin#189]
### Version of Archi, Operating System
Archi version 4.9.2 Build: 202201131438 on windows 10

### Version of this plug-in
0.8.1.202112061132

### Any other plug-ins installed?
Archi Excel Plugin
Archi Scripting (jArchi)
Archi Scripting (jArchi) Comman Line
Archi Scripting (jArchi) Examples
Lightbox for Archi

### Expected Behaviour
I expect to be able to publish the model to the newly created Master branch on GitHub even when te repository is "public"
ideally a clearer logfile on WHAT the exact issue is on connecting to github. I am assuming the issue is that there is http credentials whilst the URL is https. But am not sure how to troubleshoot.

### Actual Behaviour
I get an error message:
There was an error:
https://github.com/MvanRooijen/AVR_Core.git: not authorized

### Steps to Reproduce the Behaviour
1. Create repository on GitHub (set to public)
2. Set all information in "Preferences" of Archi
3. Click "Add Local Model to Workspace and Publish"
4. Add URL (ending on .git)
5. Add Username (git)
6. Add Password (git)
7. Keep "Store user name and password" unchecked
8. Get error message

**Comment by Phillipus** [comment]
Are you using a GitHub Personal Access Token for password?

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by MvanRooijen** [comment]
> Are you using a GitHub Personal Access Token for password?
> 
> https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Nope, just username and password.
have not created anything. Big newb here

**Comment by Phillipus** [comment]
You need a PAT.
