### ISSUE TITLE
[question] Is there a way to change remote git repo URL

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-modelrepository-plugin#190]
For example i'd like to switch between SSH and HTTPS protocols due some issues, time to time. Is there a way do this with archi colab.
Old URL:
ssh://git@mysite.org/project/repo.git
New URL:
https://mysite.org/project/repo.git

There's workaround to switch git remote within model repo folder, bu I don't know if this would work correctly.

**Comment by Phillipus** [comment]
Edit the `.git/config` file
