### ISSUE TITLE
Publish model on gitlab

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi-modelrepository-plugin#191]
### Version of Archi, Operating System

Archi 4.9.1 on WIN 10 Enterprise

### Version of this plug-in

Coarchi plug in version: coArchi_0.8.2.202202161341

### Any other plug-ins installed?

NO
### Expected Behaviour

We would like to publish some model updates.

### Actual Behaviour

We get an error "Profile reference is orphaned....
We do not get any error when doing Tools/Validate model

See images attached.

### Steps to Reproduce the Behaviour
1.
2.
3.
![2](https://user-images.githubusercontent.com/47627451/155511834-4fe6964c-45cd-42c0-b5b5-7284a536d918.JPG)
![1](https://user-images.githubusercontent.com/47627451/155511842-3856a8c5-caee-4c53-9db2-52297b25c2ce.JPG)

**Comment by chdessus** [comment]
Hello, the problem occurs only when Archi version is 4.9.1 and not when Archi Version 4.9.2.
here is a word doc that shows that we do not have any issue with Archi 4.9.2
thanks for your investigation
[Archi commit & publish.docx](https://github.com/archimatetool/archi-modelrepository-plugin/files/8132698/Archi.commit.publish.docx)
.

**Comment by chdessus** [comment]
I did make some change on the models during 1 hour. No problem to push the updates to GITLAB.
Now we did another test: delete the model from the model repository. Then we open Archi and try to import the model from GIT into the workspace. 
We get the same error.
We did the test from an installed Archi 4.9.2 version and from a portable version. same result. same error.
[Archi commit & publish.docx](https://github.com/archimatetool/archi-modelrepository-plugin/files/8133380/Archi.commit.publish.docx)


The difficulty is becoming critical. I did train 10 persons and we are trying to work collaboratively. The error prevent us to go forward. 
Thank you for your support.

If needed, I can perform son tests of any corrected coArchi plugins.

**Comment by Phillipus** [comment]
Hi,

> We do not get any error when doing Tools/Validate model

The Validator won't be of any use in cases like this, it only makes recommendations for the model (duplicates, use of objects, etc). If the model is corrupt then this will be reported when you try to save it.

Seems like the model may have got a problem when moving/renaming elements in folders and the jArchi script should fix that. But then you also say "We get an error "Profile reference is orphaned...." which is a different issue related to using different versions of coArchi.
