### ISSUE TITLE
Invalid remote: origin error

### ISSUE THREAD

**Issue by aameen79** [archimatetool/archi-modelrepository-plugin#192]
### Version of Archi, Operating System
Version 4.9.3
Windows 10 Enterprise
### Version of this plug-in
0.8.2

### Any other plug-ins installed?
No
### Expected Behaviour
Refresh Model

### Actual Behaviour
Invalid remote: origin
<img width="898" alt="image" src="https://user-images.githubusercontent.com/37726435/159705420-7fe1af5c-a181-456d-9bb5-bcbc5f69b186.png">

### Steps to Reproduce the Behaviour
1. Refresh model

**Comment by Phillipus** [comment]
Please check the online remote URL and password. Also, please use the latest version of coArchi which is version 0.8.2.

**Comment by aameen79** [comment]
I did, I use the git connection:
git@github.com:Ahmed-Zaki/SECC-DX-Framework.git
And I use v 0.8.2

**Comment by Phillipus** [comment]
For that type of URL you need to be using SSH. Use a HTTPS connection URL instead.

**Comment by aameen79** [comment]
Yes, I know, I followed the steps for creating and using SSH keys already, and I fetched the model already for the first time, but it appeared when I tried to refresh, or publish.

**Comment by Phillipus** [comment]
Then I don't know what to suggest.

**Comment by hannayrjana** [comment]
I have the exact problem, started couple days ago. Archi 4.9.3 (also first apperared on Archi 4.8.1, upgrading Archi didn't succeed), Mac OS 12.2.1 and the latest Mac OS (have tried on two separate mac's with two different Archi versions and with two different GitHub repos). I used GitHub with SSH fine previously, but then it suddenly stopped working and started to give the origin error. I have tried to generate new SSH keys, it didn't help. Keys work fine though with other git client. I really would like to know, what is the problem?

**Comment by Phillipus** [comment]
I tried it and get:

`ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.`

Not sure if JGit supports newer types.

In the meantime, suggest to use HTTPS.

**Comment by Phillipus** [comment]
Try generating a new key with the following:

`ssh-keygen -t ecdsa -b 256 -m PEM -C "yourGitHubEmailAddress"`

And change preferences identify file to `id_ecdsa`

**Comment by hannayrjana** [comment]
Yes, in the end I got the repo working by creating a PAT (Personal Access Token) in GitHub and using HTTPS URL (PAT as password)! 

But in the end, I don't know why it suddenly stopped working with SSH, as my colleague uses SSH with the same repo... ?

**Comment by Phillipus** [comment]
Read the comment above to generate a `ecdsa` SSH key.

**Comment by hannayrjana** [comment]
Thanks @Phillipus! This ecdsa SSH key seems to be working too! Great!

**Comment by aameen79** [comment]
Many thanks!

Worked with me as well :)

**Comment by Phillipus** [comment]
All good. I'll close this.
