### ISSUE TITLE
Use Main not Master in Github

### ISSUE THREAD

**Issue by leontebbens** [archimatetool/archi-modelrepository-plugin#197]
Hi, as Github has moved to naming the main branch “main” in stead of “master” for new repo’s, it would be nice when the plug-in also use “main” for new projects.
Keep up the good work!

**Comment by Phillipus** [comment]
We can't change it because it was hard coded as the primary branch years ago. If we tried to change it now, it would lead to unpredictable results. However, coArchi version 2 will support both `main` and `master` with the default being `main`.

**Comment by leontebbens** [comment]
Ok.

**Comment by entarome** [comment]
I guess there is a workaround to that... "master" branch is created upon initialization. Every new connection after initialization on gitlab hits main branch rather than master :)
