### ISSUE TITLE
github modern auth

### ISSUE THREAD

**Issue by terryrankine-ffi** [archimatetool/archi-modelrepository-plugin#198]
### Version of Archi, Operating System
Windows - Latest build

### Version of this plug-in
Windows - Latest Build

### Any other plug-ins installed?
nope - clean

### Expected Behaviour
I should be able to add a github url, I would get redirected for web-based modern auth, I would get the token for access, my connection would work.

### Actual Behaviour
I get a http(s) basic auth popup which is incapable of working as github dropped support for modern auth

### Steps to Reproduce the Behaviour
1. import from a github url.

--------------

If this has been solved - I cant find it in your readme, and I cant find the load repo from disk but connect it to git either.

Not sure how its designed to work - but didnt meet my expectations.

**Comment by terryrankine-ffi** [comment]
https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/

**Comment by Phillipus** [comment]
Please use a Personal Access Token for the HTTPS password.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by terryrankine-ffi** [comment]
Isnt the fix to extend the UI to have (PAT) in brackets where it says password and the link to the github page on how to do that?

Noting that default search in github doesnt search closed tickets - i litterally didnt find the other 6? tickets which also mention this. Nor did I stumble on the already existing webpage.

I think there is a better fix than close to help reduce the frequency of this one

**Comment by Phillipus** [comment]
There are other git hosts than GitHub. They might or might not use a PAT. We have mentioned it on the [wiki](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Troubleshooting-Connection-Issues)
