### ISSUE TITLE
I forgot primary password. What can I do?

### ISSUE THREAD

**Issue by Ugway77** [archimatetool/archi-modelrepository-plugin#199]
Hi!
I forgot primary password. And, unfortunately, I've set new primary password, hoping Archi asks me for git password.
But it just show me "An incorrect password was entered or encryption key is invalid" dialog.
What can I do to restore access? (I've tried to delete primary_key file, Archi asks me to create primary password, and then result is the same)

**Comment by Phillipus** [comment]
Once you've set a new primary password you need to re-enter the password (personal access token for GitHub) for each repository in the Authentication tab in Properties.

**Comment by JanEisen** [comment]
where did you find the primary_key file? which file path under windows? Having the same problem and no idea how to reset my primary password!

**Comment by Phillipus** [comment]
The primary password can be set in Collaboration Preferences.

See https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Setup-and-Configuration

**Comment by Phillipus** [comment]
> I changed the primary password in Collaboration Preferences.
With the new password I get "An incorrect password was entered or encryption key is invalid".

- What method did you use to change the primary password - "Change primary password and keep current encryption key" or "Set new primary password and generate new encryption key"?
- Did you note the message "When setting a new primary password, all stored passwords will be lost and need to be re-entered for each repository"? So you may need to enter the PAT/password for each repo again in the Properties tab.

**Comment by murrayhughesccdhb** [comment]
I used Set new primary password and generate new encryption key.
Entering the PAT again is no problem as I have a record of it and can gernate a new one any time.

**Comment by murrayhughesccdhb** [comment]
I fixed this problem by removing the workspace, then signed in again using the same primary password & PAT.    I recovered my changes by copying the temp.archimate file from the removed workspace. 
The problem was originally triggered by replacing an expired PAT.

**Comment by Phillipus** [comment]
Once you'd changed the primary password all you needed to do was re-enter the PAT for each repository in the properties tab.
