### ISSUE TITLE
[Feature Request] Support openssh/ed25519 keys

### ISSUE THREAD

**Issue by dratasich** [archimatetool/archi-modelrepository-plugin#201]
I followed [SSH-Authentication](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/SSH-Authentication) to setup the collaboration plugin. I tried to use my ed_25519 key to clone a model repository.
However, cloning fails with `invalid private key`, see also issue [#88].

Reasons of why to update or switch the jsch lib (e.g., to [mwiede/jsch](https://github.com/mwiede/jsch)):
* openssh disabled rsa by default
* rsa are discouraged or not possible any more in modern source code management tools

I guess I will have to fallback to https.
However, would be awesome if ed_25519 would work at some point :)
Thanks in advance!

---

### Version of Archi, Operating System
Archi 4.9.3, 202203221030
Ubuntu 22.04.1 LTS

### Version of this plug-in
Archi Collaboration (coArchi) 0.7.1.202102021056

### Expected Behaviour
successful git clone model repository

### Actual Behaviour
`Caused by: com.jcraft.jsch.JSchException: invalid privatekey: ***`

### Steps to Reproduce the Behaviour
1. Edit / preferences / setup: file path to private key ed_25519
2. Try to add a remote model with ssh URL

**Comment by Phillipus** [comment]
Please use version 0.8.7 of coArchi. This was implemented here:

https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Change-Log#version-083---april-5-2022

**Comment by dratasich** [comment]
My bad! Thanks a lot.

Works with the latest version 0.8.7 :)
