### ISSUE TITLE
Problems with Collaboration Mode - SSH related?

### ISSUE THREAD

**Issue by DrsG** [archimatetool/archi-modelrepository-plugin#203]
### Version of Archi, Operating System
Arche 4.9 - On Windows 10 -

### Version of this plug-in
 plugin version 0.8.7

### Any other plug-ins installed?
XLS and Lighbox plugin installed

### Expected Behaviour
I tried to setup the Collaborative mode.
- created and empty repo on GitHub
- created a new SSH key-pair
- Key-pair added to the ssh-agent
- Key-paire in .ssh dir
- Public key added to GitHub
- Tried to add a model to the Collaborative space

### Actual Behaviour

I got the following Error message: 
![Screenshot 2023-02-24 170944](https://user-images.githubusercontent.com/23582842/221229866-9b2d9bb5-f526-43fb-9d9d-764bd83120b3.jpg)

### Steps to Reproduce the Behaviour
Collaborative parameters: 
![Screenshot2](https://user-images.githubusercontent.com/23582842/221230140-beffaf00-5473-4682-b3e5-2c534df4e865.jpg)

**Comment by Phillipus** [comment]
I had to Google the error message and found that  “The semaphore timeout period has expired” means the SSH session timed out. I don't know why this happens. I don't think this points to anything in coArchi itself but perhaps a network problem.

> Key-pair added to the ssh-agent

This isn't necessary for coArchi. All coArchi needs is the two SSH private/public key files and a password to access the private key. You could try unchecking the "Scan .ssh folder for identity files" option and set it to the specific private key file.

**Comment by DrsG** [comment]
Ho Phil,

I tried all sorts of things but cannot get it working.

I have setup the Colab plugin as described in the documentation.
When I use the SSL URL, I get the "semaphore timeout" message.

When I use the HTTPS URL, I get the following message:
[cid:c5e9a655-dbec-49c9-906f-307fa21890d5]

The Plugin creates a local git repo (logical).
When I open the git bash to interact with that repo, I can do a git PUSH to the
github repo which I specified via its HTTPS URL.
[cid:ec37c084-ebdd-4e73-be0b-9fa23f4c4851]

So the underlying git - github  via HTTPS part is working.

If I specify the remove repo via the SSL URL, I get the following error message:
[cid:fe4d73f5-635d-4ced-8f5f-5ac8642e9c8a]

How can I make Archi working with the HTTPS URL for the remote repo?

Kind regards

Geert Haerens

________________________________

**Comment by DrsG** [comment]
Sorry but I've tried that one multiple times.
I aways get the SSL error when trying to use HTTPS
________________________________

**Comment by Phillipus** [comment]
If you are using email to reply to these messages attachments like screenshots do not appear.

**Comment by jbsarrodie** [comment]
> I aways get the SSL error when trying to use HTTPS

If you get a SSL error, then that's most certainly because you are using a SSL proxy which uses an unknown certificate. In such case, you'll have to add it into the `cacert` file included with the built-in JRE. You can find some guidance [here](https://github.com/archimatetool/archi/wiki/How-to-create-a-packaged-version-of-Archi-(including-configuration-and-plugins)#use-custom-certificates).

**Comment by DrsG** [comment]
Hi Jean-Baptise,
I think that's the case indeed - I got it working on my personal PC (no proxies) but have issues on the company PC (using a cloud based proxy).
I'll try the likin you sent.
One question, when you talk about certificates, am I right in assuming that what I need to include is the github certificate?

Kind regards

Geert
________________________________

**Comment by jbsarrodie** [comment]
> One question, when you talk about certificates, am I right in assuming that what I need to include is the github certificate?

Not really. Because you are using a corporate proxy, what Archi (or any browser) sees is the proxy's certificate, not the real github certificate. One simple way to get it is to simply connect to github using a browser and then clic on the lock icon: you'll get access to some security related information dialog which usually (on most if not all browsers) allows you to see and then export the certificate.

**Comment by DrsG** [comment]
Dear Jean-Baptiste,
Good news, the procedure works!
Thanks a lot for your fast ans excellent support !

Kind regards

Geert

________________________________

**Comment by Phillipus** [comment]
Thanks, JB, for solving this. 😄
