### ISSUE TITLE
How to configure regenerated PAT

### ISSUE THREAD

**Issue by murrayhughesccdhb** [archimatetool/archi-modelrepository-plugin#205]
### Expected Behaviour: when the old PAT has expired, the collab tool uses the regenerated PAT.
The wiki explains how to install the ergenerated PAT.

### Steps to Reproduce the Behaviour
1. Generate a PAT
2. Import the model into the workspace.
3. Wait till the PAT expires.
4. Publish changes.  
5. the collab tool gives an error

**Comment by Phillipus** [comment]
To add a new PAT you select the repository in the Collaboration Workspace, and then go to the Properties window and enter it in the Password field of the Authentication tab.

BTW - you are using a very old version of Archi and coArchi and these are unsupported.

**Comment by murrayhughesccdhb** [comment]
My problem was that I had the Collaboration Workspace view was in the same pane as the Properties view, so the workspace properties did not show. Instead, when I selected the workspace, the the Properties view showed the view properties.
Once I dragged the Collaboration Workspace view to a different pane the properties view showed the the Workspace properties just as you describe. 
Thanks
