### ISSUE TITLE
Bug when open taggle collaboration workspace

### ISSUE THREAD

**Issue by josedelarosa-ml** [archimatetool/archi-modelrepository-plugin#206]
When I try to open collaboration workspace I recibing a error bellow:

![Captura de pantalla 2023-03-15 a la(s) 4 45 11 p m](https://user-images.githubusercontent.com/92817285/225450901-95877cdc-c907-4f9f-8381-e3019bd154c1.png)

![Captura de pantalla 2023-03-15 a la(s) 4 54 10 p m](https://user-images.githubusercontent.com/92817285/225452536-1470e014-eb05-4fcf-9b01-4229cfa968b2.png)

### Version of Archi, Operating System
Archi-Mac-5.0.0, I'm using macOS Ventura

### Version of this plug-in
coArchi_0.8.7.archiplugin

### Any other plug-ins installed?
No

### Steps to Reproduce the Behaviour
1. Open Archi
2. Open menu collaboration
3. Open open taggle collaboration workspace

**Comment by Phillipus** [comment]
For some reason your system is running out of memory. One thing I don't understand in the log is the reference to Jav1 11.0.15 because Archi 5 ships with Java 17.

Can you please post the error log as text, not a screenshot?

**Comment by josedelarosa-ml** [comment]
This is the log in text:
[error-archi.log](https://github.com/archimatetool/archi-modelrepository-plugin/files/10992852/error-archi.log)

I don't know why git crashes in Archi, I'm using Visual Studio Code to work and everything works normally without problems.

**Comment by josedelarosa-ml** [comment]
Yes, I deleted the folder and everything worked.
