### ISSUE TITLE
Collaboration features don't work after Upgrade to 4.10 Mac

### ISSUE THREAD

**Issue by jmlee-de** [archimatetool/archi-modelrepository-plugin#207]
### Version of Archi
4.10

### Archi Plug-ins
Archi Collaboration (coArchi) 0.7.1.202102021056
Archi Collaboration (coArchi) Command 0.7.1.202102021056
Archi Scripting 0.8.0.202006231201
Archi Scripting Command Line 0.8.0.202006231201
Archi Scripting Examples 0.8.0.202006231201

### Operating System
Mac Ventura 13.2.1 (22D68)

### Expected Behaviour
"Commit", "Refresh Model", "Publish model" should do that on our git repository.

### Actual Behaviour
Nothing happens.

I have recently upgraded from 4.93 to 4.10. 

### Steps to Reproduce the Behaviour
1. Download
2. Open DMG.
3. Copy to Applications folder, thus overwriting the old version
4. Tried above-mentioned commands.

Please see attached logs which mention missing classes.
[log.txt](https://github.com/archimatetool/archi-modelrepository-plugin/files/10991906/log.txt)

**Comment by Phillipus** [comment]
It may be that some information has not been cleared in the cache.

Try deleting the ".config" folder located at "<user>/Library/Application Support/Archi4/.config"

**Comment by jmlee-de** [comment]
Thanks! That solved the functionality issue. I had a funny error with the identity file, but I have now fixed that.

Everything works.  I will close this issue.

Cheers
James
