### ISSUE TITLE
Status line and/or scrollable log window 

### ISSUE THREAD

**Issue by marbico** [archimatetool/archi-modelrepository-plugin#21]
Can the plug-in display a status message for the operation that has just been performed until it is manually closed? At the moment, messages flash quickly and disappear. You can not always follow the reading. What about the status bar and / or the scrollable log window?

**Comment by Phillipus** [comment]
Do you mean an information dialog like "Commit was successful" or something like that?

**Comment by marbico** [comment]
Yes. Something like that.
