### ISSUE TITLE
Unable to import remote model – empty model created instead

### ISSUE THREAD

**Issue by Qhilm** [archimatetool/archi-modelrepository-plugin#210]
### Software versions
- macOS 13.3.1
- Archi 5.0.2
- coArchi 0.8.7
- No other plugin installed

### Expected Behaviour
I paste URL "https://gitlab.domain.com/myUser/coarchi.git" and it imports the model.

### Actual Behaviour
 "new model" is created, empty. No visible error message.

### Steps to Reproduce the Behaviour
1. Collaboration > Import Remote Model to Workspace
2. Paste URL "https://gitlab.domain.com/myUser/coarchi.git" (I also tried without .git at the end) 
3. Enter username and password

### troubleshooting done:

1. Starting point: working coarchi, could commit and publish. Team member could not import.
2. navigated to https://gitlab.domain.com/myUser/coarchi/ and checked I could see my latest commit.
3. "Main" is a stale branch, my commit went to "master" branch.
4. Then I uninstalled archi and all config files on my machine to troubleshoot.
5. Reinstalled archi 5.0.2
6. Reinstalled coArchi 0.8.7
7. Tried to import, but same as my team member, I end up with an empty "new model".

There is no error log attached because "view error log" button is greyed out.

Am I typing the URL wrong somehow? Is that a problem that my model is under the "master" branch instead of the "main" one?

**Comment by Phillipus** [comment]
Hi, yes, please ensure that the default branch on the git server is "master".

**Comment by Qhilm** [comment]
thanks, I changed the default branch for this repository only to "master".

Now nothing happens at all when I attempt to import https://gitlab.domain.com/myUser/coarchi/

I also tried

https://gitlab.domain.com/myUser/coarchi/model/
https://gitlab.domain.com/myUser/coarchi.git

same result, nothing happens, no model is created or added, no error message, and the "view error log" button is greyed out.

**Comment by Qhilm** [comment]
🤦 how did I miss that...

ok, all good again, thanks a lot, you saved me!!

**Comment by jaroslavpsenicka** [comment]
thanks @Phillipus for this comment! 
this is one of the "obvious" features everyone knows... as a newcomer, I'd love to get the Collaboration Workspace opened after import, or even better - just open the newly imported model straight into the Models view
