### ISSUE TITLE
Add informations to error message in coArchi

### ISSUE THREAD

**Issue by ghost** [archimatetool/archi-modelrepository-plugin#211]
### Version of Archi, Operating System

Windows, Archi 5.0.2,
### Version of this plug-in

 coArchi 0.8.8
### Any other plug-ins installed?

jArchi

### Expected Behaviour

Would it be possible to add information  to these error messages, I hope it will help us identify the source cause ? (Actually, I am not sure the second message comes from coArchi but as we usually get it after refreshing the model..) 
- "File is not directory or folder.xml does not exist." : add folder path
-  "There was an error in model: ..... diagram connection relationship has wrong target end component" : add name/type of the connection and source name (same for wrong source end, add target name)

### Actual Behaviour

Message is only "File is not directory or folder.xml does not exist."
### Steps to Reproduce the Behaviour
well I am not sure :
1. move or delete a folder in Views
2. publish your model
3. ask a teammate to update a view that was in the moved/deleted folder
4. ask him to publish his model

**Comment by Phillipus** [comment]
Please see https://github.com/archimatetool/archi-modelrepository-plugin/issues/136

This can happen under these circumstances, unfortunately.
