### ISSUE TITLE
Feature request(s) - Repo file/folder locations/structure

### ISSUE THREAD

**Issue by nickbrownapollo** [archimatetool/archi-modelrepository-plugin#213]
Not sure if this counts as two requests, but they may be related:

1. Unless I'm misunderstanding, it looks as though each model has to reside in it's own distinct code repo. Is it possible that this could be modified so that I can keep all my models in a single repo? Feels like an additional top-level folder (using the model name?) would be needed as a container to separate each model's GRAFICO output. This feature would really reduce the amount of repo administration that I'd have to do to share all my models.

2. Can we specify the folder location for the .archimate (& .bak) files. Currently they reside in the .git folder. Unless there's a good reason for them to reside there, I'd like to be able specify a distinct location for them outside of the "Collaboration Workspace folder" location.

**Comment by Phillipus** [comment]
Hi,

1. No, sorry this can't be changed as all of the commit history relates to one model. See https://github.com/archimatetool/archi-modelrepository-plugin/issues/51

2. Sorry no, coArchi expects to see these files in that location.

Phil

**Comment by Phillipus** [comment]
I'll close this for the reasons above.
