### ISSUE TITLE
Gitlab authentication issues

### ISSUE THREAD

**Issue by frogatvers** [archimatetool/archi-modelrepository-plugin#215]
I use Archi 5.1 with CoArchi 0.8.8 and gitlab on W10.
Everything works fine from a functional point of view, but authentication is a nightmare for me.

I access gitlab with https. I need, for this, to use a Gitlab Personal Access Token (PAT). 
This PAT has not an unlimited expiration. 
After I updated the PAT, because it was expired, authentication does not work anymore.

I believe my PAT is encrypted on my laptop, with a primary key I also use.
When I want to push my updates, Archi requests me to give my primary password.
Before updating the expired PAT, it worked fine.
But after, authentication fails at gitlab level : authentication not supported.
I have in mind Archi uses my expired PAT and fails since it has changed.
But I don't know how to update the PAT in Archi / coArchi configuration. 
I imagine, based on what is explained on collaboration configuration 
I don't know where is the encrypted file containing my authentication credentials.
I imagine, again, that I need to delete this file to force Archi to ask me again my PAT and encrypt it again.

**Comment by Phillipus** [comment]
> But I don't know how to update the PAT in Archi / coArchi configuration.

Select the model/repository in the Collaboration Workspace window and then, in the Properties window, select the Authentication tab and enter the PAT in the password field.

**Comment by frogatvers** [comment]
Hello Phil, thanks a lot, it worked fine.
