### ISSUE TITLE
[BUG] Merge branch error ... 'File is not directory or folder.xml does not exit'

### ISSUE THREAD

**Issue by goodoo1000** [archimatetool/archi-modelrepository-plugin#219]
[log copy.txt](https://github.com/archimatetool/archi-modelrepository-plugin/files/14859597/log.copy.txt)

### Version of Archi, Operating System
Mac OS Sonoma 14.2.1

### Version of this plug-in
0.8.7.202212021111

### Any other plug-ins installed?
No

### Expected Behaviour
When I resolve conflicts, I expect merge to complete and request if delete the branch

### Actual Behaviour
When I resolve conflicts, I get a dialog box titled 'Merge Branch' with the following text ...
"There was an error:
  File is not directory or folder.xml does not exit"

### Steps to Reproduce the Behaviour
1.  select Merge Branch into Current Branch
2.  resolve conflicts
3.  error

**Comment by Phillipus** [comment]
Hi, please read this https://github.com/archimatetool/archi-modelrepository-plugin/wiki/File-is-not-directory-or-folder.xml-does-not-exist

**Comment by goodoo1000** [comment]
thanks very much for that ... appears I need to look deeper into this ...
