### ISSUE TITLE
SSL Problem with Netskope proxy

### ISSUE THREAD

**Issue by ascheitel** [archimatetool/archi-modelrepository-plugin#222]
Hello,

A Netskope proxy agent was recently installed on our workstations and I can no longer access my remote git repository with the coArchi plugin.
The error I get when I do a push or a refresh is "Secure connection to https://****** could not be established because of SSL problems".
I've added the Netskope certificate to the truststore as indicated in the https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Use-SSL-TLS-with-local-or-private-PKI procedure, but that doesn't change anything.

I'm interested if you have any ideas for solving this problem.

Thanks

**Comment by Phillipus** [comment]
The only info I could find on this here was this [issue](https://github.com/archimatetool/archi-modelrepository-plugin/issues/180). Unless one is on-site these things are difficult to diagnose.
