### ISSUE TITLE
Could you sign the plugin or publish a hash

### ISSUE THREAD

**Issue by salle69** [archimatetool/archi-modelrepository-plugin#226]
Hi,

Is it possible to sign the plugin so that it is possible to verify its authenticity, or at least publish a hash next to the download link, so that we could verify that it is the untampered file we've downloaded?

/Johan

**Comment by Phillipus** [comment]
Well, the great thing about this being a free and open source project is that you can build the binaries from source if you have doubts.

**Comment by salle69** [comment]
@Phillipus, is that a no?

My skillset is such that this might be an unsurmountable obstacle, but I'll see what I can do.

I still think it would be a nice service to provide at least a hash-value next to the download link when you provide pre-compiled versions. Please consider it.

**Comment by salle69** [comment]
I just found that you do this for the tool itself: https://www.archimatetool.com/downloads/archi/5.4.3/Archi-5.4.3-SUMSSHA1

Great idea!
