### ISSUE TITLE
Background model refresh

### ISSUE THREAD

**Issue by johannsmit** [archimatetool/archi-modelrepository-plugin#227]
Automatic model refresh is not working and no error log is available

### Version of Archi, Operating System
Version 5.4.3 Build 202410291006 on Windows 11

### Version of this plug-in
Version 0.9.2.202311181027

### Any other plug-ins installed?
No

### Expected Behaviour
The model should be automatically refresh every interval (60 sec.)

### Actual Behaviour
No automatic fresh is happening, I am still required to manually refresh

### Steps to Reproduce the Behaviour
1. Check "Refresh remote model status in the background" under workspace preferences
2. Set the desired refresh interval
3. Wait for a refresh to happen

**Comment by Phillipus** [comment]
Hi, this will not actually refresh the model, only the status of each repo in the Repository Workspace. So this will let you know if there have been changes on the remote repo. A refresh is still required manually.

**Comment by johannsmit** [comment]
Thanks for clarifying. Maybe a good idea to add this to the wiki?
