### ISSUE TITLE
[FEATURE REQUEST] - Add branching mechanisms

### ISSUE THREAD

**Issue by zopanix** [archimatetool/archi-modelrepository-plugin#24]
Hey, just putting the idea out. I'll probably won't have much time to work on this even if it gets accepted.

## New Feature
Add branching system to the plugin

## Description
You would have the possibility to create a new branch from the ui, and change branches from the ui.
To start I wouldn't use the ui to handle the merges. github, bitbucket, gitlab already offer pretty decent ui's to handle pull/merge requests. They also have ways of handling merge conflicts, etc.

I don't know if it would be hard, haven't even looked at the code yet. Am just throwing it out there.

## To think about if implementing the feature:
* Add the possibility to rebase a branch from another
* When pulling a change, to a --prune --rebase
** --rebase: avoid merge commits
** --prune: remove old branches from local git repo and sync it with server

**Comment by Phillipus** [comment]
Branching is on our roadmap. 

(We need to improve the History view in the plugin first I think so we can see the branch.)

**Comment by JonCSykes** [comment]
Per our discussion at: http://forum.archimatetool.com/index.php?topic=437.0

I'll go ahead and ramp up on this, it's a good one for me to get my feet wet I think. :)

**Comment by Phillipus** [comment]
Thanks, Jon.

Just to re-state, our aim is to shield the user from the "technical world of git" as much as possible. We use the git mechanism for sure, but if we can put a sugar coating on top of that, so much the better.

Regarding the History View, jGit has an API for plotting the lines:

https://github.com/eclipse/jgit/tree/master/org.eclipse.jgit/src/org/eclipse/jgit/revplot

But these have to be implemented, as they are in eGit:

https://github.com/eclipse/egit/tree/master/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/history

**Comment by teterkin** [comment]
We use _Gitflow workflow_. And if I push changes, plugin pushes it to _master_, not to _develop_, even though _develop_ is the default branch.

**Comment by jbsarrodie** [comment]
@teterkin There is no notion of 'default' branch in Archi collaboration plugin, the 'master' branch is always used.

**Comment by teterkin** [comment]
Thank you @jbsarrodie for the answer. I meant the default GitLab branch. Sorry. It would be nice to choose the branch to push to.
