### ISSUE TITLE
Login name is used for merge commits.

### ISSUE THREAD

**Issue by mpcjanssen** [archimatetool/archi-modelrepository-plugin#47]
When the plugin automatically merges remote and local changes, the name used for the merge commit is the local login name.
Instead the configured username and email from the configuration should be used. For example:

Configured user = Mark Janssen
Configured email = mark.janssen@domain.com
Windows 10 user = Mark

```
commit 610e4a3ad35faff6316be86cac2ff7d65c543a1b
Merge: 56c9305 86fac84
Author: Mark <personal-email>
Date:   Mon Sep 11 17:09:25 2017 +0200

    Merge branch 'master' of https://therepo/reponame.git

commit 56c930560863ab327c46ca81b62e4459e5c8df77
Author: Mark Janssen <mark.janssen@domain.com>

   The commit message
```

**Comment by Phillipus** [comment]
I suspect that in cases of automatic merge JGit looks for the username and email from the global .gitconfig file. If not present, then uses a system property.

I can change this so that it reads from .gitconfig and updates this when the plug-in preferences are saved.

**Comment by mpcjanssen** [comment]
@Phillipus that would be a sensible solution.

**Comment by Phillipus** [comment]
I've created a new release at:

https://www.archimatetool.com/plugins

- This stores the global name/email set in Preferences in ~/.gitconfig 
- You can also set a different name/email per repository/model by selecting the repository in the Collaboration Workspace and then showing "Properties". A new "User Details" section has been added. These over-ride the global mail/email.
- If the global name/email is set then the name/email for each repository in Properties will display it in grey text. Effectively the setting is blank. You can over-ride the global settings by editing the two fields.

**Comment by Phillipus** [comment]
To be clear:

- If global name/email is set in Preferences this will be used for all commits and merges
- If a local name/email is set in Properties for a repository/model this is used for all commits and merges otherwise the global name/email is used

**Comment by Phillipus** [comment]
And:

- If no global name/email exists in Preferences (.gitconfig) then the first time these are entered in a Commit dialog these are stored as the global settings 
- If global name/email does exits then changing these in the Commit dialog will store them in the local config for the repository

**Comment by mpcjanssen** [comment]
What is there against always storing the name/email in the repository settings?

I purposely don't set my global email for git to prevent leaking of work email in public repos or public email in work repos. The solution as it stands seems to set the global email after the first commit.

**Comment by Phillipus** [comment]
>The solution as it stands seems to set the global email after the first commit.

This was done to provide a default for users who have not set global prefs.

**Comment by mpcjanssen** [comment]
If it would be an option to force storing the name and email in repository settings only, that would be great. As it stands, it breaks my use of global and local settings.

**Comment by Phillipus** [comment]
If we get rid of this it might help:

- If no global name/email exists in Preferences (.gitconfig) then the first time these are entered in a Commit dialog these are stored as the global settings

**Comment by Phillipus** [comment]
Removed that last option. .gitconfig name/email can only be set from Preferences now. If not present these are stored for each repo.

**Comment by mpcjanssen** [comment]
Thanks, commits look good. Will test before closing.
