### ISSUE TITLE
[Feature] Allow the copy/past, move, import/export of specific elements between models

### ISSUE THREAD

**Issue by samperd** [archimatetool/archi-modelrepository-plugin#48]
As an architect
I want to easily copy/move elements from one model repository to another repository
So that I can re-use elements, split large models, or combine multiple small models.

Details:
( I tried doing a copy and paste on a windows file system from one local model repository to another. This did not work even after a restart of Archi.
* Perhaps we need a git-add feature to add copied files
* it would be great is Archi itself support click and drag of elements between projects.

**Comment by samperd** [comment]
Update:
I also tried the following in windows file explorer

1. copy elements from one local model repository (motivation folder) to another local model repository (nothing adding to model in Archi yet)
2. right click and open Git GUI
3. select each unstaged file to add to commit list (see notes below) (Still not in Archi)
4. Add commit message and comitted to local repository (Still not in Archi)
5. committed model in Archi (likely should have done this first- Still not showing changes in Archi model)
6. Close and reopen archi (still no new elements)
7. Publish to remote (still no change)
8. refresh model from remote (still no change)

So I am not sure how to add elements. I tried everything that makes sense to me from a GIT and Graphico perspective.

Cheers

Notes:
* See section "adding stuff to the repository" here: http://matthew-brett.github.io/pydagogue/git_gui_windows.html
* both commits from GIT GUI and Archi show up in Archi's "Change history"

**Comment by jbsarrodie** [comment]
Hi,

Being able to create view using elements comming from several models is something that would be great and is in the (my head's) roadmap ;-) This doesn't have to even use git features but only EMF (Eclipse Modelling Framework on which Archi is based) ones.

What you've tried would work using the legacy Grafico plugin but doesn't in the model repository plugin because the model is "cached" in a .archimate file, so changing manually the content of the local git repo is not "seen".

What you've described in the latest comment should work (and I've already used it several time). Basically Archi doesn't check if the remote git repo has been change by the plugin or any other mean, so if you manage to commit a change that adds the right XML files, the plugin will see this as changes on the remote and will sync them on refresh or publish.

Regards,

JB

**Comment by samperd** [comment]
So it looks like that at some point the copied files are blown away. I will try to narrow it down:

Welcome to the rabbit hole. how deep will we go? 

Successful steps: 1, 2, 3, 4
Failed Steps: 
     5: DO NOT commit through Archi. Use GitGUI to commit
     6. Skip
     7. Push from Git GUI

Up to this point files can be added, committed and pushed to remote git repository.

So to refresh the project with the new files added I try to:
1. Refresh model within archi. Result: I am forced to "commit" before a refresh. and even if I bail the files are removed from the local repo
2. Do a remote pull/fetch using Git GUI I don't see the new files show up.

Result: I am left with a local repo missing the copied elements and a remote repo with the copied elements that will not synch on a git pull/fetch. Therefore I still have a local repo without copied elements.

So next I went to "Change history" and the latest event was the forced commit which removed all the work I did in Git GUI. But the second last activity was the commit and push that worked for the remote. So I tried:
1. Select message
2. Right Click > extract model from this commit
     result: The elements I added to the model show up. So I thought I would commit this model, but the collaboration tools are greyed out.
3. Right click > restore to this commit. Created two copies of model each with their own git hash ref. (not what I wanted)
4. Reset to remote commit (now I have three model projects)
5. Closed all models (right click on each model with Git HASH's)
6. in the original model I can now see the copied elements, however they are greyed out
7. Tried to commit, but forced to save
8. After save, elements are still greyed out.

I guess I am still confused on how a good workflow should work.

**Comment by samperd** [comment]
I think I have a solution now

Ignore the greyed out issue. I had the wrong "viewpoint" setup for the element.
Still learning Archi.

So do we have a streamed workflow now?
1. In windows explorer copy elements from one local repo to another
2. Use the GIT GUI to add, commit, push to remote repo
3. From Archi, refresh model (forces commit which results in Local Git repo droping newly added files)
4. In Archi, go to change history and UNDO last commit (forced in previous step)

Result: Copied elements show up in model.

This is a little convoluted, but could work for now.

Suggestions:
1. allow the right click of a model element in Archi when using collaboration plugin, in an information tab provide the GIT Hash/FileName of the file so you can find the element you are looking for on file system easier. (alternatively include full name of element as part of the file name. Append githash at end. eg (ELEMENTTYPE-ELEMENTNAME-GITHASH)
2. Handle copying of elements directly in Archi (Long term goal)
3. When you "refresh" from a remote DO NOT force a commit. Present a warning message instead to the user and allow user to refresh without committing local changes.

**Comment by jbsarrodie** [comment]
The fact that you are prompted to do a commit when refreshing means that you have changed something in Archi. This is not a "forced" commit.

**Note**: I know someone who faces a strange behavior: he's prompted to do a commit every time he uses the refresh action, even if he did no changes. IN such case, the resulting commit is empty (checked with SmartGit) and then an unneeded merge is done with remote.

Here is what I've done numerous time without any issues:
Given that I have added a model in Archi's Collaboration workspace
1. Do a git clone of the remote repo in another, new folder
2. In this new local clone, add any needed XML files
3. In this new local clone, do a commit and then push to remote
4. In Archi, you can now do a refresh or a publish that will merge the newly pushed commit with your work.

When reading you I'm not sure you copy files on another clone of the repo. To be clear you can't manage the local clone created with Archi like a usual git repo, any action at git level (outside Archi) must be done on another clone.

>alternatively include full name of element as part of the file name. Append githash at end. eg (ELEMENTTYPE-ELEMENTNAME-GITHASH)

The filename can't be like that as it must not change when the element is changed. Including ELEMENTNAME break this rule. In addition, what you call GITHASH is not that, this is the Archi internal Id of the element (the one you can see when exporting the model to CSV).

**Comment by Phillipus** [comment]
>  I know someone who faces a strange behavior: he's prompted to do a commit every time he uses the refresh action, even if he did no changes. IN such case, the resulting commit is empty (checked with SmartGit) and then an unneeded merge is done with remote.

That might be another line endings issue. This might depend on OS and other setup variables. Might be worth checking the line endings with another tool.

But isn't all of this just a hack to merge and combine elements of models? Better to address this at the core of Archi?

**Comment by jbsarrodie** [comment]
>But isn't all of this just a hack to merge and combine elements of models? Better to address this at the core of Archi?

Yes, that's the whole point of this feature Request which aim to (I cite) "re-use elements, split large models, or combine multiple small models.". Let's discuss this next week ;-)

**Comment by samperd** [comment]
Here is a related issue. There is a new [Government of Canada public architecture repository](https://github.com/canada-ca/architecture) on github now. As an "architect" I would love to re-use components from the GC level in my architectures at a departmental or project level. I have capture this issue with that context here: [Extracting Reusable Architectural Components ](https://github.com/canada-ca/architecture/issues/5).

Hopefully Archi can help move towards federating architectures, maybe automatically pulling various upstream sources into one?

What would adding this feature cost if its was to be sponsored?

**Comment by jbsarrodie** [comment]
There is some work going on toward this goal. Read this [wiki](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/%5BDiscussion-for-main-2018-Sprint%233-feature%5D-Merge-of-an-'external-model'-into-'main-model') page to see the direction we're taking. Comments are welcome.

**Comment by rctheinventor** [comment]
This is relevant to my interests - I recently started on some new architecture work that is arms-length from the Canadian government.  I'm using archimate as my modelling language and Archi as my modelling tool.

**Comment by jbsarrodie** [comment]
_Some updates:_

The _modelimporter_ feature added to Archi 4.7 (still in early access) will solve this using the folowing list of actions:
1. Open the model you want to copy element from. Save it as another model (locally).
2. In this copy of your source model (let's call it "partial model"), keep only views and concepts of interrest and then save it. This can be done (e.g.) by deleting any unwanted views and then running a script like [this one](https://gist.github.com/jbsarrodie/aae4ed4981ada94834cfdf48d978a13f)
3. You can close your "partial model".
4. Now open your target model and use the new modelimporter feature (File > Import > Another Model into Selected Model) to import your "partial model" into the target model.

As nothing much will be added, I'm closing this issue.
