### ISSUE TITLE
Error when clone the repository with Git

### ISSUE THREAD

**Issue by rromerito** [archimatetool/archi-modelrepository-plugin#60]
The repository used is GitLab ee. I can't clone the entire repository because the name of the files is too long.

![error-git_clone](https://user-images.githubusercontent.com/17601637/43852699-6b20f3dc-9b2d-11e8-95da-482160d496a6.JPG)

**Comment by Phillipus** [comment]
Seems like there's lots of sub-folders. Definitely an issue for investigation.

**Comment by jbsarrodie** [comment]
Hi, you should try using another Git client (e.g. SmartGit) or maybe a more recent version of git. Could you also check which filesystem you use (FAT or NTFS).

I've faced it in the past: there's a limitation under Windows but it depends on the filesystem and the way you create files (either through absolute or relative path). This has been fixed in recent (<1y) versions of git but some GUI comes with an older version).

**Comment by Phillipus** [comment]
Could we split the id string of the folder to make them shorter anyway? I need to investigate how we handle folders, but I think the idea is simply to make them unique.

**Comment by jbsarrodie** [comment]
This error is not raised by the collaboration plugin but by a git clone from another git client. This is an OS related limitation which is well managed by JGit (and SmartGit and maybe most git client). I don't seen a reason to change yet.

I don't think that using something other than UUID is a good idea.

**Comment by Phillipus** [comment]
It may be a problem.

Folder IDs are long like this - 8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed - this is 36 chars. Windows has a 260 path limit.

On my Windows 10 machine I can't have a folder path longer than this. This is only 4 levels deep:

C:\Users\phillipus\AppData\Roaming\Archi4\model-repository\archisurance-demo\model\business\8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed\8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed\8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed\8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed

**Comment by jbsarrodie** [comment]
>Folder IDs are long like this - 8d8c695c-6e7a-4bb7-8214-57bdf2adc5ed - this is 36 chars. Windows has a 260 path limit.
>On my Windows 10 machine I can't have a folder path longer than this. This is only 4 levels deep:

This is a limitation of explorer.exe, not the underlying filesystem. See https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file :

>The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters.

**Comment by rromerito** [comment]
Thank's guys. All your answers were very helpfull.
Best regards. 
;)

**Comment by jbsarrodie** [comment]
So how did you solved your issue at the end (could help other users of TortoiseGit)?
