### ISSUE TITLE
Change "background" fetch behavior on failed authentication

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-modelrepository-plugin#62]
_Summary of our email discussion_

Most clients/organisation use an identity management platform which provides a single sign on feature to all enterprise applications. This means (in my case but that's very similar for other archi users I know) that the user account and password I use on BitBucket is my universal Id at Accenture. So when I import a model in my collaboration workspace in Archi, I have to provide my universal Id and password (the same I use to logon on windows, outlook...). What happened is that I asked Archi to remember my password to enable background fetch. Some month later, I had to change my password (mandatory every 3 months, as in most organisations). After than, Archi continued to (try to) fetch in background. Of course it failed, but it kept retrying at the normal "pooling interval". This didn't raised any issues in Archi itself (nothing got wrong). The issue is that each time Archi tried to fetch, our global indentity management platform saw this as a failed attempt to connect. And as in many organisation, after 3 unsuccessful log on, my account got locked for some hours, so I wasn't even allowed to open a session on windows or access my emails.

So to avoid that, we should make sure that when a background fetch fails due to a bad password, then we should no more try with the same password. 

>_(Phil's comment)_
It's easy enough to tag a failed login attempt in the Fetch job per Archi session and not try again, but the same could happen over different sessions. An option is to delete the user credentials file if this happens, but it may be just a bad connection. Or we could stop the Fetch Job and display an error message? And then what happens?

The best (and usual) thing to do is to just remove the password, not the whole credential file, so that the user will simply have to enter his new password for the next refresh or publish. In this case, the checkbox to save user/password should be checked by default. Of course, this assumes that the fetch job will notice that the file exists but with an empty password.

Are we able to know if the issue is because of bad credential or something else (e.g. bad connection) ? If yes we could dissociate behavior for those two cases.

>_(Phil's answer)_
The problem is that the same TransportException is thrown if credentials are wrong, if a bad connection, or something else. The only difference is each exception's text message which is risky to depend on (it might change).

Before doing the fetch, do we check the network connectivity of the remote ? If yes, then there is a good chance that the exception is related to a credential, if not, then there is a good chance that the exception is simply related to the PC being offline (FWIW, I and other colleagues/clients work almost 50% of the time offline).

In addition, If a user have imported several models/repository using the same credential, then the password should be removed from those credential files as well if it is the same (or else the cumulated number of failed logon attempts will soon lock the "enterprise' user id).

>_(Phil's answer)_
It's a tricky one. We want to disable fetch if there is a known credentials error but we can't be 100% sure if it is one. Then we would be intrusive and delete the password from all repositories credential files on this assumption. And we need to let the user know about this.
>
>What we could do is:
>- Fetch Job fails with TransportException
>- Show Dialog - "Background Fetch has failed for repo {repo}. Do you want to cancel background fetching for this session or try again or reset passwords for all repositories that share these credentials?"

Sounds like a good direction (if we are sure the issue is not simply the PC being offline).

**Comment by Phillipus** [comment]
It's not easy to differentiate what the TransportException is caused by except for the exception's text message.

If I set a wrong username or password, the exceptions can be:

`org.eclipse.jgit.api.errors.TransportException: https://bitbucket.org/user/repo.git: not authorized`

or

`org.eclipse.jgit.api.errors.TransportException: https://bitbucket.org/user/repo.git: authentication not supported`

If I work offline the message is:

`org.eclipse.jgit.api.errors.TransportException: https://bitbucket.org/user/repo.git: cannot open git-upload-pack`

I would rather avoid testing the text error message, as this is really a human readable message not a proper error code or status.

**Comment by Phillipus** [comment]
Looking at the JGit source code (`org.eclipse.jgit.transport.TransportHttp`) I think that the connection might even be attempted up to 3 times.

At this point I'm thinking that we need to test the connection with credentials first, somehow. I don't know if this can be done with something else than JGit.

**Comment by jbsarrodie** [comment]
In fact what we really need is a network connectivity check with the git server:
- If network (directly or through proxy) is not available
  - then retry later (ie. user is offline)
- if network is available
  - then try a fetch
    - if ok, good
    - if ko, prompt the user and show the error message from exception. The user will decide if it's worth stopping background fetch or not.

**Comment by Phillipus** [comment]
Is background fetch working now if you are behind a proxy? There's no proxy check in the code other than in the main UI actions.

**Comment by jbsarrodie** [comment]
>Is background fetch working now if you are behind a proxy? There's no proxy check in the code other than in the main UI actions.

I don't know as I don't use a proxy (either full local or unfiltered).

I should be able to setup an authenticated firewall on my cloud VM ;-) I will let you know when done.

**Comment by Phillipus** [comment]
It doesn't initially. If you do an action like Refresh it then does because that sets up the Proxy. The authentication and proxy code needs a bit of an overhaul.

**Comment by Phillipus** [comment]
I'm still working on the best solution for this. However...

It seems the only way to test for authentication success or failure is by doing a Fetch action and checking the exception message string. I asked here https://www.eclipse.org/forums/index.php/t/1095487/ but don't expect an answer.

How many times of trying should we allow? Let's say there are six repositories, should all six be tried or should we stop after the first authentication failure?

Also, there's not an easy way for the user to reset/edit username and password at the moment so that needs doing.

**Comment by jbsarrodie** [comment]
Ok, some remarks on this...

I wasn't expecting this to be a big challenge, so maybe we should remove it from our current sprint backlog (we'll have lots to do for branching)..;

That being said...

MVP
* The best MVP so far is to simply add a way to disable it from preferences. This will allow users to save their credentials without the risk to lock their account when passwords change. 
* This also requires (as you noticed) an easy way for the user to reset/edit credentials. I'd suggest to do it from the repository's properties tab.

Not MVP (long term)
* Find a way to check network connectivity. This might be through a proxy, so we should be able to distinguish between real network issue and authentication error on the proxy.
  - If we face an authentication error on the proxy, then we should warn the user so that he can decide to disable background fetch or reset its proxy password.
  - If we face a network connectivity issue then we should simply wait a bit before retrying
  - If connectivity is ok then continue
* Try to fetch from the imported repositories...
  - If we face an error, then we know it is not related to network nor proxy, so it might be an authentication error, so we prompt the user to warn it. This message must expose the name of the impacted model and the error string, so the user will decide (we don't parse the error). We should offer the following options:
    1. Do nothing (ie. retry later)
    3. Disable background fetch for this repos (ie. remove password from credential file).
    4. Disable background fetch for all repos that use the same account (ie. remove password from credential file)
    2. Disable background fetch for all repos
    - In all cases, we should explain how the user can change its password (e.g. from the repo's properties tab)
