### ISSUE TITLE
"Amend last commit" should not be possible after a merge commit

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-modelrepository-plugin#63]
_Summary of our email discussion_

We should not be able to amend last commit when last commit is a merge commit (it seems we can today)

>_Phil's remark
This is possible to do generally in git (trued it in SmartGit), but I can understand that for us it might complicate things. The issue here is determining exactly what is a "merge commit" as in the logic of "If the last commit was a merge commit, don't offer the option to amend last commit.") Is it a commit with more than one parent?

Yes, exactly

BTW, I remember an edge case which led to some big issue: I'm not absolutly sure of the sequence but it was something like:
- I made some changes on a model
- Someone else made and published some changes in parallel
- I decide to publish my changes
- There's some conflicts, so I'm asked to solve them
- I simply take note of the issue but cancel the conflict solving process because I don't want exactly "mine" or "theirs" but a mix of both
- I change the model element in conflict (so that I can now choose "mine" which as become the mix I wanted)
- I commit my changes using the "amend last commit" option (because I want to update my previous own change)
- I decide to publish my changes
- The model is published

But, BUT... Noticed that the model has been published without asking me to solve the conflict? I have in fact pushed my version and not the merge of my version with "theirs". That's because the first merge attempt led to a "still in progress" merge commit that haven't got clean up. So when I asked to "amend last commit", I have in fact amended (and "finalyzed") the merge commit with my own version of the model (because Archi has regenerated all XML files from my model).

So we have not only to forbid "amend last commit" for merge commit, but we should also make sure that any canceled merge attempt is well cleaned up.

_Update after our initial email discussion_
This could be the root cause behind [this issue raised on the forum](https://forum.archimatetool.com/index.php?topic=575.0).

**Comment by Phillipus** [comment]
There's a fix for this now.  "Amend last commit" is not enabled if the previous commit has more than one parent. Cancelling the dialog box has always cleans up the merge state so the only time this might not get cleaned up is if there is an exception. so I've put a clean up action there too.
