### ISSUE TITLE
Can only publish changes with Master level and above permissions 

### ISSUE THREAD

**Issue by KingBain** [archimatetool/archi-modelrepository-plugin#69]
Hello, 

not sure if anyone else has noticed this, but I cant seem to publish changes( in archi) to a privately hosted gitlab repository when I have developer level access. 

If I change the access to Master then a publish is successful. 

I also receive no errors in Archi when I try to publish or commit the changes.

**Comment by jbsarrodie** [comment]
Seems to be an issue on your configuration as I have several colleagues working with GitLab without any issues (and they're not Master, only developer). Can you double-check?

If you don't use your password but some Token/API key, check that the Token has been created with right access-right.

Check also that you don't enforce commits to be done using the exact same email as the one of your gitlab account if you configured the plugin with another email.
