### ISSUE TITLE
Github certificate problem

### ISSUE THREAD

**Issue by jvdongen17** [archimatetool/archi-modelrepository-plugin#70]
Version of Archi, Operating System
Archi 4.1.1.
Github SCMManager

Expected Behaviour
Refresh of model from Github

Actual Behaviour
Error on certificate by refresh.
error message
![error message](https://user-images.githubusercontent.com/35136585/47782555-c767b080-dd00-11e8-9fb1-206ae7840802.png)

Steps to Reproduce the Behaviour

**Comment by jvdongen17** [comment]
Hi,

I got this as a tip from a friend.

please check your version of git with
> git --version
If this version is above 2.14 then proceed, else upgrade git first and proceed

Use following commandline to accept ssl certificates:
> git config --global http.sslBackend schannel

**Comment by jvdongen17** [comment]
A re-install of the latest versions done, but same error still occurs.

**Comment by Phillipus** [comment]
As the plug-in uses the JGit library, it's not affected by any Git installation.

This sounds like some kind of certificate issue, but I'm not the best person to solve this. I Googled it and came up with issues to do with cert files in Java like this - https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

Anyone else have this issue and solved it?

**Comment by jbsarrodie** [comment]
@jvdongen17 I'm not sure to fully understand your issue. Could you be more precise on the type of Git server you're using. In several places you speak about GitHub, but you also speak about SCMManager which is not related at all (and not related to Archi neither).

Based solely on your error message, I would suspect that you are using a Git server which uses either a self-signed certificate or a certificate from an internal PKI. In both cases, you have to manually add the certificate in the cacert file of the JVM used by Archi (usually the one provided by Archi itself).

You can find some basic documentation about adding your own certificate to the cacert [here](https://github.com/archimatetool/archi/wiki/How-to-create-a-fully-portable-(Windows)-version-of-Archi-(including-plugins)#optional).

**Comment by jvdongen17** [comment]
Adding the certificate to Cacerts did the trip to make it work again

Thx both for your help
