### ISSUE TITLE
302 error

### ISSUE THREAD

**Issue by jvdongen17** [archimatetool/archi-modelrepository-plugin#75]
When I refresh my client I got an 302 error.
![archi_error](https://user-images.githubusercontent.com/35136585/48231990-74e95c80-e3b0-11e8-9c80-c766468208d6.png)

Does anybody know what it means and how to handle?

Jurgen

**Comment by jbsarrodie** [comment]
Hi,

HTTP 302 is the code for redirection. This means that the server which hosts your model has been changed and the URL has changed too. The old URL is still listening for connection and tries to redirect you to the new one, but this doesn't work with Git.

You have to get the new URL, remove the model from your workspace and reimport it with the new URL.
