### ISSUE TITLE
Error during publish

### ISSUE THREAD

**Issue by WayneCBarker** [archimatetool/archi-modelrepository-plugin#76]
Hi, I am trying to setup a collaboration environment between me and another architect.

We are using Archi 4.3 Build  201809101333 and plugin org.archicontribs.modelrepository_0.3.6.201809112225.

I can pull fine from github. When I publish and the other guy tries to refresh it works 100% until he tries to publish then he gets the same error again.

We deleted his local repository and did a fresh get but got the error again.

See the attached image.

btw - What is the difference between commit and publish? 

![3597f131](https://user-images.githubusercontent.com/3244770/48706498-22583d80-ec05-11e8-913f-a2304be548fa.PNG)

**Comment by Phillipus** [comment]
It could be a number of things, including connection problems, or proxy settings. Unfortunately, the error message reported by the JGit library doesn't help. Is he able to connect and download the repo initially?

**Comment by WayneCBarker** [comment]
Ok thanks, I had to make the other guy an owner and that resolved it.

**Comment by Phillipus** [comment]
Closed as sorted
