### ISSUE TITLE
Unable to reset/change password for a remote git (bitbucket) repository

### ISSUE THREAD

**Issue by oligatorr** [archimatetool/archi-modelrepository-plugin#79]
Hello 

I use Archi in connection with a Bitbucket git repository. The password is regularly updated on the server but I am not able to figure out how to set the new password in Archi. The consequence is that Archi seems to use the outdated password and then lock my access to the bitbucket repository: 
![capture d ecran 2019-02-19 a 11 03 09](https://user-images.githubusercontent.com/31451875/53006877-6d693300-3436-11e9-8baa-2b307a7c275b.png)

I have then to unlock manually the bitbucket repository. 

I have tried to go into the git local directory (/Users/myname/Library/Application Support/Archi4/model-repository/digital-arch ) and reset properly the password there. If I do git fetch in this directory it does work but it did not help when trying to use Archi collaboration plugin from Archi itself.

Thank you in advance for your help 

Olivier 

![capture d ecran 2019-02-19 a 11 11 12](https://user-images.githubusercontent.com/31451875/53007221-19ab1980-3437-11e9-9790-96e39a1d51d7.png)

![capture d ecran 2019-02-19 a 11 12 37](https://user-images.githubusercontent.com/31451875/53007314-49f2b800-3437-11e9-8f05-820940cbe111.png)

**Comment by Phillipus** [comment]
We've made this simpler in the latest Alpha release available from the Releases section here. You can select the repo in Archi and in Properties tab change user credentials.

For previous version of the plug-in you could set in Archi Preferences not to store passwords in an encrypted file and it will prompt you again for a new password.

Or you can manually delete the "credentials" file in the  /Users/myname/Library/Application Support/Archi4/model-repository/digital-arch/.git folder. This folder will be hidden on a Mac.

BTW - Archi 4.3.3 is now available and fixes a lot of issues.

**Comment by Phillipus** [comment]
We've released version 0.4.0 GA - https://www.archimatetool.com/plugins/

This should solve your problem if you:

- Select the repo in the Collaboration Workspace
- Right-click and select "Properties" to open the Properties window if it is not already open
- Select "User Details" tab in the Properties window
- Click the "Edit..." button in the Authentication section to set a new password

**Comment by oligatorr** [comment]
OK thanks I just tested the "simple solution": remove the credentials file and it worked. I will test the new versions later on. I guess we can close this ticket !

**Comment by oligatorr** [comment]
@Phillipus  I just tested the new collaboration version and it is far better now with the branch support and the edition of the credentials. Great Job !

**Comment by Phillipus** [comment]
@oligatorr Thanks! Also thanks to @jbsarrodie who is the lead on this project.

Bear in mind that this is still really "beta" and some features are still being worked on and there will be bugs. ;-)

**Comment by etienne-sf** [comment]
Hello,

For those interested, with the 4.9.3 version I use, the `credential` file to remove is:
`C:\Users\your_name\AppData\Roaming\Archi4\model-repository\cosmos_model\.git\secure_credentials`

Etienne
