### ISSUE TITLE
Question: where is the archimate file stored on PC?

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi-modelrepository-plugin#80]
Is this the underlying archimate file used when the model is connected to github:
C:\Users\<user>\AppData\Roaming\Archi4\model-repository\<reponame>\.git\temp.archimate

The reason I ask is I've encountered a situation where I have a model in github with uncommitted changes.  I've been working with a number of other local models on my PC and I've exceeded the list size of the Open -> OpenRecent menu option.

So, I was unsure  which local file to re-open to resume modifications to the gihub model. 

Further, when I look at the file C:\Users\<user>\AppData\Roaming\Archi4\model-repository\<reponame>\<modelname>.archimate, it is out of date with changes I've made to the model.

**Comment by Phillipus** [comment]
That temp file is used to load into Archi from the various small xml files. The proper way to open a model that has been connected to a repo is through the Collaboration Workspace. The temp file is synchronised internally.

**Comment by Phillipus** [comment]
Closing if OK.
