### ISSUE TITLE
[BUG] Branch selection lag while switching model repositories.

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-modelrepository-plugin#84]
## Environment
Archi version: 4.3.3
archi-modelrepository-plugin: 5.0
JDK: Oracle JDK 8
l0calhost:~$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

## Steps to reproduce:
1. Connect and pull 3 model repositories or more
2. Select model repository in "Collaboration" workspace
3. Go to "Branches" workspace
4. Go to  "Collaboration" workspace
5. Select other model repository
6. Go to "Branches" workspace
7. Go to "Collaboration" workspace
8. Go to "Branches" workspace

## Expected behaviour:
Branches lit are displayed for the selected model repository accordingly.

## Actual behaviour:
At step  6 we still can see branches list for the previously selected model repository.
At step 8 we can see branches list for the newly selected model repository.

**Comment by Phillipus** [comment]
I tried to reproduce this but can't.

Are you on Windows? Can you simplify the steps to reproduce it? I tried your steps with 5 repositories in the Collaboration Workspace.

**Comment by WatchTh1** [comment]
Linux. Ubuntu 18.04 LTS.

вт, 5 мар. 2019 г. в 01:01, Phil Beauvoir <notifications@github.com>:

**Comment by WatchTh1** [comment]
I'll try it in my Windows environment.

вт, 5 мар. 2019 г. в 01:02, Alexander Luchkov <al.luchkov@gmail.com>:

**Comment by Phillipus** [comment]
Tried on Linus Mint (Ubuntu based).

I'm selecting alternately between Collaboration Workspace and Branches View, back and forth. And all seems OK.

I must be missing something here?

**Comment by WatchTh1** [comment]
I'll make a video and link it here. If there are some additional info
needed, just tell.


вт, 5 мар. 2019 г. в 01:16, Phil Beauvoir <notifications@github.com>:

**Comment by WatchTh1** [comment]
Link to bug reproduction video:
https://www.youtube.com/watch?v=KkfyWHUARuY

**Comment by Phillipus** [comment]
OK, the problem arises when opening and closing the Branches View from the toolbar.

When opening the Branches View from the toolbar it is activated with the focus, and so the focus is lost on the Collaboration Workspace and therefore doesn't update.

If you keep the Branches View open all the time the it will synchronise with the selections in the  Collaboration Workspace

However, this will be fixed in the next version.

**Comment by Phillipus** [comment]
The same is true for opening and closing the History View from the toolbar.

Also will be fixed in the next version.
