### ISSUE TITLE
[BUG] Model repository is not selected by default when model is selected in "Model tree"

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-modelrepository-plugin#85]
# Use case: Switching branches
Launching Archi and opening model repository 1st time in work session

## Prerequisites
User has connected model repository.
Model is imported in workspace.
Archi is shut down.

## Steps
1. Launch Archi
2. Select model and make some work on it in "Model tree"
3. Commit work.
4. Open "Branches" workspace

## Expected behaviour
There are list of branches for the selected model.

## Actual behaviour
Branches list is empty until manual selection is not done in "Collaboration" workspace.

## Proposed behaviour
Select corressponding model repository when working with model tree.

**Comment by Phillipus** [comment]
This is expected behaviour. The link is between the Collaboration View and the Branches View.

**Comment by WatchTh1** [comment]
Yeah, that's expected, that model repository SHOULD be selected to see branches list.

Unexpected is that I don't have selected one by default and it is is not linked with model selected in model tree.

Could it be promoted as feature request?

**Comment by Phillipus** [comment]
> Could it be promoted as feature request?

I'll see if it is possible.

**Comment by Phillipus** [comment]
Will be fixed in the next version - selecting a model in the Models Tree will select the corresponding model in the Collaboration View (and therefore also the Branches View).
