### ISSUE TITLE
[feature] Plugin localization

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-modelrepository-plugin#86]
Is there any way to localize this plugin as it is done for other plugins with archi-nls project?

My case is to let analyst and PM team to use archi (view/simple changes and so on), and there would be a good case to get localized messages.

I would even propose to include this plugin in main distribution (and therefore modify nls settings accrodingly to support plugin localization), but don't know how it seems to you.

**Comment by Phillipus** [comment]
Localisation is the same process as with other plugins.

> I would even propose to include this plugin in main distribution

Too soon for that. Keeping it separate means we can update it quicker when there are bugs and new features. Archi update cycle is slower.

**Comment by WatchTh1** [comment]
I'll try to make it happen and go up with manual/distro then.
How do you think, would it be of use to store localized plugin
distributions amongst eng versions?

вт, 5 мар. 2019 г. в 12:42, Phil Beauvoir <notifications@github.com>:

**Comment by Phillipus** [comment]
We can link to them on our Resources page on the website.

**Comment by WatchTh1** [comment]
That's fine. Then I'll provide github release links as soon as they are
ready.

вт, 5 мар. 2019 г. в 12:55, Phil Beauvoir <notifications@github.com>:
