### ISSUE TITLE
Project is seen modified without any modification [Collaboration plugin v0.5.0]

### ISSUE THREAD

**Issue by rchevallier** [archimatetool/archi-modelrepository-plugin#91]
After importing brand new a remote model inside archi (plugin v0.5.0, archi v4.4 beta2), the collaboration thinks there are modification.  Trying to do a simple refresh makes it ask to commit changes before although there were absolutely no modification.

Using "Abort uncommitted changes" action doesn't make any difference. 

System: Windows 10

When looking with git, there is an empty change for the model.xml file

~/workspace/models/gluttony (master)$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   model/folder.xml

~/workspace/models/gluttony (master)$ git diff model/folder.xml

~/workspace/models/gluttony (master)$

**Comment by Phillipus** [comment]
This will be because you are using Archi 4.4. The metamodel version number changes inside of model/folder.xml `version="4.4.0"`

**Comment by rchevallier** [comment]
Indeed. Any functional impact if an older version of archi is modifiying the model  or everyone working on the model must have the same version?

**Comment by Phillipus** [comment]
> Any functional impact if an older version of archi is modifiying the model or everyone working on the model must have the same version?

No. It's just a nuisance.

When the Archi metamodel is updated in a new version, the metamodel `version` attribute is updated (which may or may not be the same version number as Archi itself). So this shows up as something that needs to be committed.

I guess we need a way to indicate this to the user somehow. Needs some thought.

**Comment by jbsarrodie** [comment]
>Needs some thought.

I already thought about it and have some ideas for future features... I just need to find some funding for that  :-(

**Comment by Phillipus** [comment]
See #92
