### ISSUE TITLE
Git repo in admin dir instead of user dir (windows)

### ISSUE THREAD

**Issue by PieterGit** [archimatetool/archi-modelrepository-plugin#94]
Conditions:
- Archi 4.4 Beta 3
- Model Repository Collaboration Plugin 0.5.0
- Windows 10
- I installed the Model Repository Collaboration Plugin under normal (non administrator) account, with "Start Archi as administrator"

Results:
- Local Git repo is installed as
`C:\Users\adminuser\AppData\Roamding\Archi4\model-repository\archimate\.git\temp.archimate`
- This is shown in the title bar of the window

Expected result:
- I would expect the local git repo in the users directory (non administrator account).

If you can point me to how this can be solved I can try to create a PR, but I'm completely new to the codebase

**Comment by Phillipus** [comment]
The default is <user.home>, so you can change it in preferences if you want. You only have to run Archi with admin rights to install a plugin so it can write to the Program Files folder, you don't have to be logged in as admin.
