### ISSUE TITLE
[Feature Request] Local Git repositories

### ISSUE THREAD

**Issue by Petrolevb** [archimatetool/archi-modelrepository-plugin#97]
It would be nice to be able to add a remote that is on local computer (URL should be able to manage /home/user/anything or C:\Users\anything)

**Comment by cgoguyer** [comment]
Is there some news about this feature? As git support file repository, it would be nice to store data without a server.

**Comment by Phillipus** [comment]
No news. It hasn't been implemented (yet). I've been too busy with other Archi features.

**Comment by smirnoww** [comment]
+1. I also need this feature

**Comment by GuyWicks** [comment]
A rough workaround to this is to manually create a git repository on your pc and then use file:///c:/localrep/.git/ as the URL with a dummy username/password

> c:
> cd \
> mkdir c:\localrep
> cd localrep
> git init
Inititalized empty Git repository in c:/localrep/.git/

then use file:///c:/localrep/.git/   when creating a repository in Archi


This, by default creates the git repository on your local PC's (I'm using Windows) %APPDATA%/Roaming directory - but if you change this to a better location then it should work.

And then you get the benefit of the commit and branching features.

The only trouble is, how do you get your existing XML based models into the new model - that old chestnut!

And I've not tested this on a network share with multiple people though...

**Comment by jbsarrodie** [comment]
@GuyWicks : In fact, you should be able to use a FILE based URL even at the beginning, ie. when importing the model into the workspace. Of course the publication will fail, but the repository will have been created and will be usable for later commits (at least it used to work 2 years ago the last time I tried).

**Comment by cgoguyer** [comment]
I've setup a file repo on a remote share (git init --bare) the import, commit, refresh button work but I get an error with the publish button: "error during unpacking on remote end: error cannot lock pack". 
But If I use the git push command in my local repo it works.
The error appear only within archi UI.

**Comment by aheizenreder** [comment]
+1. I also need this feature.

**Comment by Phillipus** [comment]
Perhaps something to consider for coArchi 2.
